### ISSUE TITLE
Bikeshed source file linting

### ISSUE THREAD

**Issue by domenic** [whatwg/meta#1]
Here are some things it would be nice to have Travis verify for us, for all the Bikeshed-using specs:

- Line length, I guess ignoring inside `<pre>` blocks---any other exceptions?
- No trailing whitespace

Please add more ideas!

**Comment by annevk** [comment]
Line length might be tricky as I don't wrap "inline" elements (I never quite remember the new terms). I guess you could detect that since the start and end tag are on the same line.

**Comment by foolip** [comment]
I had some terrible code in https://github.com/w3c/webvtt/blob/gh-pages/format.py and https://github.com/WICG/mediasession/blob/master/format.py that could possibly be reduced to just a linter. Reformatting isn't an impossible problem, although not wrapping "inline" elements makes it harder and I never bothered.

**Comment by annevk** [comment]
https://github.com/whatwg/resources.whatwg.org/issues/51 is something that seems reasonably simple to add.

**Comment by annevk** [comment]
Going to close this in favor of https://github.com/whatwg/whatwg.org/issues/66 which has a concrete working suggestion, but needs a few more tweaks.

It doesn't tackle line length (see also #31), but I don't think we have a good way to deal with line length exceptions yet. Once someone figures that out it seems that repository would be the place to make the suggestion.
