### ISSUE TITLE
Bitmap favicons?

### ISSUE THREAD

**Issue by ricea** [whatwg/meta#10]
Browser support for SVG favicons is patchy. Favicons are useful in distinguishing tabs for people who keep many open. It would be nice to have PNG fallbacks for WHATWG specs for those of us whose browsers don't support them.

**Comment by annevk** [comment]
Wouldn't it be better to complain to the relevant browser?

**Comment by ricea** [comment]
Many people have: https://bugs.chromium.org/p/chromium/issues/detail?id=294179 :-)

**Comment by domenic** [comment]
This would be a one-line change to the Bikeshed template to add the .png version as well. I wonder about the extra bandwidth usage (since they're 500x500 instead of sized appropriately), see e.g. http://www.hanselman.com/blog/FavIconicoCanBeABandwidthHog.aspx . But maybe it's fine.

**Comment by annevk** [comment]
I'd rather not do it because it gives less incentive for browsers to fix their bugs. I'm pretty sure Firefox fixed their bug in part because of WHATWG Standards.

**Comment by zcorpan** [comment]
I agree with @annevk.

**Comment by ricea** [comment]
My interpretation of the Chrome bug is that implementing SVG favicons would be roughly equivalent in difficulty to implementing HTML favicons.

I don't dispute that it's an excellent feature, but WebGL favicons would be pretty awesome too.

**Comment by annevk** [comment]
That sounds wrong. It's just as hard as supporting SVG in image. You just need to generate a bitmap from it and use that.

**Comment by foolip** [comment]
It's actually harder than that. In Chromium, the code that handles favicon loading (I think) and rendering is outside of Blink (web platform bits) entirely. One would have to start a renderer for the favicon, which would be roughly equivalent to HTML favicons.

**Comment by annevk** [comment]
https://chromium-review.googlesource.com/c/chromium/src/+/1541185

Hurray!
