### ISSUE TITLE
Updated JS MIMEs under 2 week review from IETF

### ISSUE THREAD

**Issue by bmeck** [whatwg/meta#102]
https://datatracker.ietf.org/doc/draft-ietf-dispatch-javascript-mjs/ is under review and has a mailing list thread open about it at https://mailarchive.ietf.org/arch/msg/dispatch/X3aBzTbPFT8bJRAYcO7ldjJmAls

Please respond with any endorsements or concerns.

**Comment by annevk** [comment]
How does this relate to https://github.com/bmeck/I-D/issues?

**Comment by bmeck** [comment]
@annevk I don't think it is necessary to close all issues to move forward. After the 2 week review the I-D will undergo a revision to comments left during the review period.

I never got feedback on responses in some issues and tend to leave them open for people to easily see in the UI unless some significant consensus is reached. I probably won't be closing issues just because I feel they are out of scope, but I did reply to https://github.com/bmeck/I-D/issues/17 , https://github.com/bmeck/I-D/issues/16 , and https://github.com/bmeck/I-D/issues/19 a while back. Lack of response could let me close them, but it seemed more prudent to leave them open since nor response doesn't mean agreement.

**Comment by annevk** [comment]
I recommend folks track this at the IETF directly at this point.
