### ISSUE TITLE
Documentation on URL syntax

### ISSUE THREAD

**Issue by EnnexMB** [whatwg/meta#104]
Hi, I have a suggestion for the URL documentation, probably section 4.5. "[URL serializing](https://url.spec.whatwg.org/#url-serializing)". 

It would be helpful to include a formulaic representation of the URL syntax. It seems that the syntax is defined in section 4.5, and that syntax could be represented as:

[scheme](https://url.spec.whatwg.org/#concept-url-scheme):[//[[[username](https://url.spec.whatwg.org/#concept-url-username)[:[password](https://url.spec.whatwg.org/#concept-url-password)]@][host](https://url.spec.whatwg.org/#concept-url-host)[:[port](https://url.spec.whatwg.org/#concept-url-port)]]][{[path](https://url.spec.whatwg.org/#concept-url-path)0|/path1[/path2[…/pathn}][?[query](https://url.spec.whatwg.org/#concept-url-query)][#[fragment](https://url.spec.whatwg.org/#concept-url-fragment)]

Is there a way to propose the addition of this syntax formula to section 4.5 or another appropriate section of the documentation? Or have I just made that proposal by filing this issue?

**Comment by zcorpan** [comment]
Can you open a new issue for this in the whatwg/url repo?

**Comment by annevk** [comment]
See https://github.com/whatwg/url/issues/337.
