### ISSUE TITLE
Contributing guidelines should say something about submitting issues

### ISSUE THREAD

**Issue by zcorpan** [whatwg/meta#107]
@andershol

> (I did read the contributing guidelines, but as I read them, they only talk about submitting pull requests and not about submitting issues)

https://github.com/whatwg/html/issues/3983

**Comment by andershol** [comment]
Note that I did not argue for anything to be added to the guidelines. New rules should IMHO only be added if they are needed. My comment referred to the note appearing to the right of the form on the "new issue" page. For people that have not opened an issue before it says "It looks like this is your first time opening an issue in this project! Be sure to review the contributing guidelines." (for other people it just say "Helpful resources Contributing"). So you could just remove those seemingly irrelevant reminders/warnings. Most other github projects don't seem to need those.

**Comment by zcorpan** [comment]
I think that's something GitHub does, not something we can control. In any case, I think it can make sense to discuss submitting issues in the contributing guidelines.
