### ISSUE TITLE
Document that IRC requires +r

### ISSUE THREAD

**Issue by annevk** [whatwg/meta#108]
Unfortunately there's too many spammers these days. Let's point this out on https://whatwg.org/irc.

**Comment by ryzokuken** [comment]
@annevk I'd like to pick this up. How exactly are you envisioning this UX-wise? Some form of notice? Should it go in the "IRC" section or the "Getting started with IRC one"?

**Comment by domenic** [comment]
Thanks @ryzokuken for the fix! It's live on https://whatwg.org/irc#getting-started-with-irc.

I'm going to tweet out a call for people who haven't used IRC before to test our new instructions, and ask them to report back to this issue to see if the instructions are clear enough.

**Comment by ryzokuken** [comment]
@domenic sounds fair. I'd love to make any further changes to improve the help text.
