### ISSUE TITLE
Tweets are done via GitHub services, which are being deprecated

### ISSUE THREAD

**Issue by domenic** [whatwg/meta#109]
https://developer.github.com/changes/2018-04-25-github-services-deprecation/

We use https://github.com/github/github-services/blob/a71f251994d146e43843b9e6659da87ecdb03a58/lib/services/twitter.rb

They will be removed from the web interface 2018-10-01, and stop working 2019-01-31.

I don't see any ready-made replacements or alternatives, unfortunately. So probably we have to build our own webhook and deploy it somewhere on whatwg.org. I have some experience doing this in Node for participate.whatwg.org already.

This is probably a good chance to make improvements; the existing truncation logic in the Twitter service is bad and often chops links in half. We could even do things like tweeting only the commit headline, or filtering to remove Editorial: and Meta:-prefixed commits.

/cc @keithamus as my go-to GitHub person in case there's something we missed, e.g. a replacement for the Twitter service.

**Comment by annevk** [comment]
* https://gist.github.com/kylefrost/f3841e76749dc64f4b5e
* https://github.com/and-computers/HowToTweetEveryCommit

Some kind of script that deploy.sh could invoke would be neat.

**Comment by domenic** [comment]
https://developer.github.com/actions/ may be another replacement

**Comment by zcorpan** [comment]
I've used https://zapier.com/ which works OK, and was easy to set up for a single thing, but might be annoying (and maybe not free) for many things.

**Comment by tabatkins** [comment]
Did this ever get fixed? If so, how? (@frivoal just noticed that the CSSWG bot stopped working Jan 31 last year, exactly on the turndown date ^_^)

**Comment by domenic** [comment]
Sadly no :(

**Comment by frivoal** [comment]
Seems easy to do with both zappier or automate.io, and the free plan of the later stretches to a higher number of tweets/commits per month

**Comment by tabatkins** [comment]
It shouldn't be hard to do by hand, either, and that would mean we're not depending on a 3rd-party service's free tier.

(Just run a webhook that posts using the Twitter API. I already have something set up to post tweets via the API, I'd just have to figure out what info I get from webhooks.)

**Comment by frivoal** [comment]
Sure, but we can set up automate.io first in like 1 minute for $0, then we have a working (if temporary) solution while you find time to do it properly

**Comment by domenic** [comment]
@annevk and I talked a bit about getting this re-started. Here would be my suggestion: Let's reuse the `participate.whatwg.org` repository and infrastructure, as it's already running a server and already dealing with GitHub webhooks.

In particular, I'm envisioning:
- A file, call it `compose-tweet.js`, in https://github.com/whatwg/participate.whatwg.org/tree/main/lib which exports a "pure function" which takes in a GitHub webhook request body (or maybe just a subset of it?), and outputs a tweet, something like `{ account, tweetText }` or `null`. This handles logic like filtering out `Editorial:` and `Meta:` tweets, and trimming the text to just the commit message title, and adding the proper link to the end.
  - This file can then be extensively unit-tested in a pretty simple way in https://github.com/whatwg/participate.whatwg.org/tree/main/__tests__ ; no complicated mocking would be needed.
- A file like https://github.com/whatwg/participate.whatwg.org/blob/main/lib/pr-webhook.js, call it `tweet-webhook.js`, which uses `compose-tweet.js` to process incoming webhook requests, and uses the Twitter API to post the tweet.
  - This could also be unit tested, similar to https://github.com/whatwg/participate.whatwg.org/blob/main/__tests__/pr-webhook.js, although it'd need a good deal of mocking, and might not be worth it if the logic is not extensive.
  - We need to figure out how to tweet from JavaScript. @annevk points to https://www.npmjs.com/package/twitter-lite
  - This file would also need to get the appropriate Twitter credentials, presumably to feed to twitter-lite. We can probably just put them in `private-config.json`; be sure to update https://github.com/whatwg/participate.whatwg.org/blob/main/private-config.sample.json
  - The exact division of responsibilities between this file and `compose-tweet.js` is flexible. E.g., maybe this file should take care of figuring out the account? I'm not sure what would be ideal, and it's probably a matter of taste.
- Then you need some small glue to invoke the `tweet-webhook.js` function when a HTTP request comes in: copying https://github.com/whatwg/participate.whatwg.org/blob/53132edcff3a59460d44d301cfb46edce675cb36/lib/routes.js#L134-L143 should suffice.
- Don't forget to update the README.

With the webhook set up, we can then configure it similar to how we do for the participate status check webhook, as documented in https://github.com/whatwg/participate.whatwg.org#setting-up-the-github-webhook. Alternately, we could consider using an organization-wide webhook. The latter would probably just involve filtering more events in the early parts of the webhook.

**Comment by annevk** [comment]
Progress:

* We also need a CLI to associate Twitter accounts with whattweetbot (a reincarnation of WebAppsTweet) and get the keys to be able to tweet on behalf of those accounts. I created a prototype that seems to work and shared it with @domenic.
* @domenic and I discussed that it might be good to have an organization-wide webhook and let participate.whatwg.org filter. This reduces the amount of configuration we have to do for each repository. I set this up as `/github-webhook` so we can get some example data for tests.
* I created https://github.com/whatwg/participate.whatwg.org/pull/158 for participate.whatwg.org changes to allow tweeting. It will acknowledge the author of the commit in the tweet if they are not the author of the specification.

I think we're nearly there.

**Comment by domenic** [comment]
> @domenic and I discussed that it might be good to have an organization-wide webhook and let participate.whatwg.org filter. This reduces the amount of configuration we have to do for each repository. I set this up as /github-webhook so we can get some example data for tests.

I was still envisioning two separate webhooks, each only triggered on some events. participate.whatwg.org would then only do the repo filtering, not the event filtering. That seems a bit cleaner to me than getting hit with every event.

**Comment by annevk** [comment]
We don't get hit with every event, it would still just be push and pull_request (you can select those you want), but they would go to a single endpoint. Having to configure the GitHub side twice and duplicating the secret seems a little less clean to me.

**Comment by domenic** [comment]
I'm thinking of future webhook setups. If in the future we want to react to other events, then we need to configure our mega-webhook for the union of 3+ underlying webhooks? I'd prefer maintaining a 1:1:1 correspondence between configured webhooks, with their specific events they deal with, `*-webhook.js` files, and routes (URLs) on the server.

At first I also felt that duplicating the secret seemed a bit weird, but I think it's OK to treat the secret as "org-wide". It's just a mechanism to ensure that only GitHub is hitting those endpoints, instead of random internet traffic. So factoring it out into the general shared webhook infrastructure (in code, `validate-github-webhook.js`) makes sense.

So concretely, my suggestion would be (and end state of) two org-wide hooks:

- `/webhooks/participation-status` which accepts `pull_request` events
- `/webhooks/twitter` which accepts `push` events

and then in the future, we might add new ones following this pattern. For example, hypothetically if we wanted to do PR previews through this infrastructure, we could do `/webhooks/pr-preview` which accepts `pull_request` events, and then GitHub would send `pull_request` events to the two separate endpoints, each of which could proceed in parallel and succeed/fail independently, instead of having the server need to internally run both then surface a single success or failure back.

**Comment by annevk** [comment]
There is a limit to the number of webhooks, but it's more than ten. In that future we might see some redundant traffic though with the benefit of slightly cleaner code in routes? I.e., instead of invoking two functions for a push, each push would have its own endpoint that invokes the relevant function. Seems fine, but irks me a bit. Your call.

**Comment by domenic** [comment]
Yeah, I'd rather invoke two endpoints for a push; that feels more like how webhooks are intended to be used. Let's keep them separate.
