### ISSUE TITLE
Problem with flattening assigned nodes

### ISSUE THREAD

**Issue by orstavik** [whatwg/meta#115]
There are some problems with flattening assigned nodes of slot elements.

I've set up the following example to illustrate the problem:
[slotFallbackCSS.txt](https://github.com/whatwg/meta/files/2428061/slotFallbackCSS.txt)
or see here:
https://codepen.io/orstavik/pen/dgyWMM

The technical problems are:
1. You write a custom element "A" that uses another custom element "InsideA". "InsideA" has a slot, and "A" places its own slot element there. "InsideA" also has default content that will be used if it is not slotted any content. If element "A" wishes to allow its users to slot in content via itself to "InsideA", how can "A" achieve this?
2. When content is shown from within the slot of "InsideA", the css rules from "A" seems to trump the css rules of "InsideA".

**Comment by annevk** [comment]
Sorry I missed this, but this is better raised at w3c/webcomponents or whatwg/dom.
