### ISSUE TITLE
Permission 

### ISSUE THREAD

**Issue by DVUed** [whatwg/meta#118]
Hello,
My name is Ken and I am a Copy Editor for DeVry, Inc. I apologize if I am contacting the wrong person – if you are not the individual with whom to speak, if you could please forward this request to the correct contact it would be greatly appreciated.
We would like permission to use your cite in our course for lecture and discussion.

Please advise if we have your permission to direct students to these links during course lectures/discussion.
Thank you

**Comment by annevk** [comment]
Hi Ken, I'm not sure I understand, but in general you should feel free to link to resources. Reusing or incorporating resources can be done per the terms of the applicable license, which is quite liberal. Hope that helps.

**Comment by DVUed** [comment]
This does help. We would just like to provide students with additional educational resources to supplement the material within the course. Your approval is sufficient. Thank you for corresponding quickly.

________________________________

**Comment by annevk** [comment]
Great, happy to help. Will close this then.
