### ISSUE TITLE
Show GDPR popup

### ISSUE THREAD

**Issue by bertyhell** [whatwg/meta#126]
Proposal for a similar API as the location API to show a popup to be compliant with the [GDPR legislation in europe](https://eugdpr.org/).

## Problem
Currently every website implements their own popup to be GDPR compliant. This results in a poor user experience where the user has to dismiss multiple popups to be able to read the actual content of the webpage.

Examples:
https://www.google.com/search?q=gdpr+popup&tbm=isch

Example library that generates these popups for you. (useful to see what options we could include in this API)
https://cookie-script.com/

## Solution
To improve this we could create an API in the browser that allows website developers to request a popup to be shown to the user. Similar to the location API popup.

![image](https://user-images.githubusercontent.com/1710840/54069983-f6b49e00-425b-11e9-8e12-2dac5e8279bd.png)

In pseudo code this API would look something like this:
```
navigator.privacy.getCookieConcent({cookie: true, tracking: true}, allowHandler, denyHandler);
```

This would then show a dialog to the user:
![image](https://user-images.githubusercontent.com/1710840/54070243-d8e83880-425d-11e9-954b-61399c05b700.png)

This would might make it possible to circumvent the GDPR popups for users that check the "use these settings for all sites" (not sure if this is legal though * lawyer assistance needed *)

This would also allow the browser to give more info about the website privacy settings:
![image](https://user-images.githubusercontent.com/1710840/54070287-4d22dc00-425e-11e9-8b6f-a0eda7a9d8a7.png)

## Discussion points:
* Is this repo the correct location to propose this API?
* Do you think this is a viable API?
* Would browsers implement this even though it is only for the European market?
* Is the "use for all sites" setting enough consent from the user to not show this dialog on other websites?
* Should we provide options for privacy tracking, so the user can consent to some tracking. eg: tracking for analytics, but not for marketing.
* Should this work with callbacks or promises or both?
* Should we include a "read more" link in the API, so users can read more about why privacy tracking consent is required for that particular website?

**Comment by annevk** [comment]
This might be a good topic for https://discourse.wicg.io/.

**Comment by bertyhell** [comment]
> This might be a good topic for https://discourse.wicg.io/.

I recreated the post:
https://discourse.wicg.io/t/proposal-show-gdpr-popup/3433
