### ISSUE TITLE
Can't access website from Russia

### ISSUE THREAD

**Issue by hinell** [whatwg/meta#130]
Hi.

I'm unable to reach the site hosted at https://html.spec.whatwg.org from Russia.
Not sure where I'm supposed to report this issue. 

It seems like that intermediate hosts block traffic coming from Russia in the US. 
Any ideas?

### tracert log

```
Tracing route to html.spec.whatwg.org [165.227.248.76]                                 
over a maximum of 30 hops:                                                             
                                                                                       
  1     3 ms     2 ms     2 ms  xxx.xxx.xxx.xxx                                            
  2     5 ms     8 ms     4 ms  xxx.xxx.xxx.xxx                                          
  3     2 ms     2 ms     *     xxx.xxx.xxx.xxx                                           
  4     3 ms     2 ms     3 ms  91.247.31.34                                           
  5     4 ms     3 ms     6 ms  msk-zoo-b2-ae4-vlan52.fiord.net [93.191.9.212]         
  6    46 ms    46 ms    47 ms  frankfurt-nt-b1-ae5-vlan550.fiord.net [62.140.239.139] 
  7    49 ms    49 ms    52 ms  xe3-3-6.franco71.fra.seabone.net [89.221.34.254]       
  8    49 ms    50 ms    49 ms  et4-0-5.franco32.fra.seabone.net [89.221.34.117]       
  9    47 ms    47 ms    47 ms  ffm-b4-link.telia.net [62.115.149.0]                   
 10   131 ms   143 ms   137 ms  ffm-bb3-link.telia.net [62.115.114.88]                 
 11   134 ms   141 ms   134 ms  prs-bb3-link.telia.net [62.115.123.13]                 
 12   134 ms   134 ms   139 ms  ldn-bb3-link.telia.net [62.115.134.93]                 
 13   135 ms   134 ms   134 ms  nyk-bb4-link.telia.net [62.115.113.20]                 
 14   151 ms   134 ms   135 ms  nyk-b3-link.telia.net [62.115.139.151]                 
 15     *        *        *     Request timed out.                             
....
 30     *        *        *     Request timed out. 

```

### Note
* `62.115.139.151` -[IP lookup info](https://extreme-ip-lookup.com/62.115.139.151)

**Comment by annevk** [comment]
I noticed this before: https://twitter.com/annevk/status/1098509091998220289.

Per https://isitblockedinrussia.com/?host=https%3A%2F%2Fhtml.spec.whatwg.org%2F the current block was enacted last April. If you know of ways to escalate this within Russia that'd be appreciated.

**Comment by hinell** [comment]
@annevk 
Oh yeah, I see. That's sad. 
Have you tried to send letter to that agency as was suggested [here](https://twitter.com/serj_zavolzhski/status/1098767399703248897)?
And what about other options like mirroring site on the other host/ip?

**Comment by annevk** [comment]
I have not. It does not say where to send the letter and whether they accept them in English. And it might not work for non-residents anyway?

I'm not aware of anyone looking into other options.

**Comment by hinell** [comment]
@annevk 
They have contacts listed here: https://eng.rkn.gov.ru/contact/
There is also link which can get you to the request form. It is in Russian though but it's simple.

I'm not sure it they will respond to non-resident but I think it's worth to let them know your opinion. 
I have already sent one in Russian [here (Russian)](https://twitter.com/biteofpie/status/1144711284316917761) It's accompanied with demands to lift the ban.

If you gonna contact them you have to know that they blocked IP while trying to block telegram messenger facilities. The court decision does says nothing about aforementioned IP or domain either. Their actions are completely illegal and not justified. 

>I'm not aware of anyone looking into other options.

Are there other ways to access the specification?

**Comment by sideshowbarker** [comment]
> Are there other ways to access the specification?

I guess it’d be possible for somebody to set up a proxy, but I’m not sure — because https://html.spec.whatwg.org/ is HTTPS-only, so for the TLS to work, it seems like we’d need to add the domain name of the proxy to the cert we’re using for https://html.spec.whatwg.org/ as an Alt Name.

**Comment by sideshowbarker** [comment]
> Are there other ways to access the specification?

https://htmlspec.herokuapp.com/multipage/ is a proxy instance I set up today.

It’s not (yet) blocked in Russia: https://isitblockedinrussia.com/?host=https://htmlspec.herokuapp.com

You can also easily deploy your own proxy instance to Heroku in just 2-3 minutes, with 5 commands:

```
git clone https://github.com/sideshowbarker/htmlspec-proxy.git
cd htmlspec-proxy
npm install
heroku create
git push heroku master
```

Sources at https://radiant-reaches-60358.herokuapp.com/multipage/

**Comment by TimothyGu** [comment]
It also [appears](https://isitblockedinrussia.com/?host=https%3A%2F%2Fhtml.spec.whatwg.org) that the block is active on the IP range `165.227.0.0/16`:

```
NetRange:       165.227.0.0 - 165.227.255.255
CIDR:           165.227.0.0/16
NetName:        DIGITALOCEAN-19
NetHandle:      NET-165-227-0-0-1
Parent:         NET165 (NET-165-0-0-0-0)
NetType:        Direct Allocation
OriginAS:       
Organization:   DigitalOcean, LLC (DO-13)
RegDate:        2016-10-06
Updated:        2016-10-06
Ref:            https://rdap.arin.net/registry/ip/165.227.0.0
```

So the issue is less that WHATWG is blocked than that all of DigitalOcean's IPs in this range are blocked. We can't really change that.

**Comment by hinell** [comment]
@sideshowbarker Thanks. There is a small issue with styles. They are served from `https://resources.whatwg.org/` so they fail to load.
 
@TimothyGu 
>all of DigitalOcean's IPs in this range are blocked

Looks like. I don't ask to unblock anything obviously. Just looking for another way to reach specification except via WHATWG site. Currently I have access to the site through standard `http`/`socks` proxies but not sure for how long it would work.

**Comment by annevk** [comment]
It seems this is fine again. Hopefully it stays that way.

**Comment by annevk** [comment]
Reopening per https://twitter.com/ocokanet/status/1231881033471139840 and verifying with the above links, but I'd need a clearer set of instructions to make such a request. (And ideally someone who writes Russian would do it, I suppose.)

**Comment by domenic** [comment]
Seems unblocked again...

**Comment by hinell** [comment]
@domenic Yup, I can cofirm that.
