### ISSUE TITLE
Enabling secure video watermarking client side in Video, MSE and EME workflows

### ISSUE THREAD

**Issue by webziggy** [whatwg/meta#138]
I would like to begin a discussion about the possibilities of rendering a video watermark on the client side in a secure layer for browsers compositing video frames from one source and a watermark generated as a bitmap/svg(?) from another. With the possibility that the watermark changes overtime. Also suggested: the browser (rendering client) and the video object collaborate and expose events to recognise tampering, resulting in failed playback when DRM-protected videos are being rendered.

(Note that A/B Variant watermarking proposed elsewhere as a solution is inherently broken)

Is there anyone who would like to discuss the possibilities of this in the WHATWG group? 

Keywords: content protection; drm; piracy; digital rights management; mse; canvas; eme; cdm

**Comment by annevk** [comment]
You're probably better off at https://discourse.wicg.io/.
