### ISSUE TITLE
Unify definition panel styles

### ISSUE THREAD

**Issue by domenic** [whatwg/meta#139]
Currently, we are using the Bikeshed-generated `.dfn-panel`, which is styled via inline styles, on most specs. We are then using the Wattsi-generated `.dfnPanel`, which is styled via standard.css, on HTML.

We should instead be using a uniform class name, with styles in standard.css (and no inline styles). Probably the best path is to:

- Modify standard.css to style `.dfn-panel` instead of `.dfnPanel`. (Do not merge until the next step is complete... or maybe better, have a period where both are present.)
- Change HTML/Wattsi to use `.dfn-panel`.
- Revive https://github.com/tabatkins/bikeshed/pull/1287/files so that it removes the inline styling for `.dfn-panel`, instead letting `standard.css` take care of it.

**Comment by annevk** [comment]
There's a corresponding issue in that definition panels also come with script (script-dfn-panel), but we could tackle that separately probably.

**Comment by domenic** [comment]
We've made some progress on this, although the way in which Bikeshed changes frequently has left us with a not-totally-unified state. There's not much more we can do here I think.
