### ISSUE TITLE
Shutting down the WHATWG mailing lists

### ISSUE THREAD

**Issue by foolip** [whatwg/meta#153]
This is a tracking issue for the plan proposed in https://github.com/whatwg/misc-server/issues/75#issuecomment-561625392 to close the WHATWG mailing lists:
> Since the volume on these lists is so low and the effort to keep them working indefinitely non-trivial, the new plan I'd like to propose is:
> - Make the list addresses auto-reply with a message saying they're no longer active and pointing out how to communicate instead.
> - Redirect lists.whatwg.org to https://web.archive.org/web/20140626155146/http://lists.whatwg.org/pipermail/whatwg-whatwg.org/ and/or the W3C archives as best we can, maybe depending on the requested URL.

This issue is filed in case someone is following this repo but not the mailing list, and yet has feedback on the plan.

The pull requests that implement the suggestion are https://github.com/whatwg/whatwg.org/pull/269 and https://github.com/whatwg/misc-server/pull/120.

**Comment by foolip** [comment]
I've found that although http://lists.whatwg.org/ says "The list overview page has been disabled temporarily", the archive pages are accessible and I'd like to make some effort to save them:
http://lists.whatwg.org/pipermail/commit-watchers-whatwg.org/
http://lists.whatwg.org/pipermail/help-whatwg.org/
http://lists.whatwg.org/pipermail/implementors-whatwg.org/
http://lists.whatwg.org/pipermail/whatwg-whatwg.org/ (partial because of some mishap in 2017)

**Comment by domenic** [comment]
Those are not accessible on HSTS-enabled browsers though, right?

**Comment by foolip** [comment]
They're not, but they appear to be the full archives of help and implementors lists, so scraping them like we did with the forums is probably low enough effort that it's worth saving.

**Comment by foolip** [comment]
I announced the proposed change on the list itself and pointed to this issue here:
http://lists.whatwg.org/pipermail/whatwg-whatwg.org/2019-December/000148.html
https://lists.w3.org/Archives/Public/public-whatwg-archive/2019Dec/0000.html

Can anyone confirm they got that email, just to be sure?

**Comment by zcorpan** [comment]
I got the email.

**Comment by foolip** [comment]
I've been digging into what archives exist and what could be reconstructed. Current understanding:
- http://lists.whatwg.org has full archives of everything except whatwg@whatwg.org prior to 2017
- https://lists.w3.org/Archives/Public/public-whatwg-archive/ has all of whatwg@whatwg.org but with different message IDs assigned, and a mapping is non-trivial
- "Gzip'd Text" links and most (all?) of the per-month Thread/Subject/Author/Date listings from the beginning to mid-September 2014 are in https://web.archive.org/web/20140626155146/http://lists.whatwg.org/pipermail/whatwg-whatwg.org/ + https://web.archive.org/web/20140913083816/http://lists.whatwg.org/htdig.cgi/whatwg-whatwg.org/

With significant effort the original state of lists.whatwg.org can probably be reconstructed apart from September 2014 through July 2017. In that period https://lists.w3.org/Archives/Public/public-whatwg-archive/ is the only copy, so at best one could recreate a listing with other numbers that are plausible, but it wouldn't match the original URLs, whatever they were.

Doing some wget scraping now to figure out how complete the web.archive.org copy is.

**Comment by zcorpan** [comment]
Does anyone have the full archives of whatwg list locally? If I remember correctly, there was a header `Archived-At` with the URL of that email in the archive.

**Comment by kosek** [comment]
I have all emails from that period locally in my Thunderbird. So I can export them make available to someone who is willing to recreate archive. But there is no Archive-At header.

**Comment by foolip** [comment]
@zcorpan the version of mailman and configuration probably changed a fair bit over time, so it's possible the headers changed. Or possibly you're thinking of the Message-ID header from which one could construct permalinks?

**Comment by zcorpan** [comment]
No it contained a URL. But it was probably only for W3C lists...

**Comment by foolip** [comment]
Yeah, I see `Archived-At: <CAOOOkFcWW97r8yg=SsWg7GgCmp4suVX9o85y8BvNRqMjuc5PXg@mail.gmail.com>` as a header on the email I sent about closing the lists.

Looks like this might actually be useful in an unexpected way! Pulling a Message-ID from https://web.archive.org/web/20140706121731/http://lists.whatwg.org/pipermail/whatwg-whatwg.org/2009-December.txt.gz and creating the URL works, I end up at https://lists.w3.org/Archives/Public/public-whatwg-archive/2009Dec/0103.html. With that I think a mapping can be created.

**Comment by foolip** [comment]
So clearly I've gone down the path of trying to keep whatwg@whatwg.org archive URLs from before  prior to 2017 working where possible, or rather to revive them as they're currently 404.

Some notes:
- There's an [Wayback CDX Server API](https://github.com/internetarchive/wayback/tree/master/wayback-cdx-server) allows for querying [all archived pages](http://web.archive.org/cdx/search/cdx?url=lists.whatwg.org/*&collapse=original&output=json), of which there are ~120k.
- Both [htdig.cgi](https://web.archive.org/web/20140913083816/http://lists.whatwg.org/htdig.cgi/whatwg-whatwg.org/) and [pipermail](https://web.archive.org/web/20140626155146/http://lists.whatwg.org/pipermail/whatwg-whatwg.org/) URLs have been used. They appear to be aliases on the current deployment, but don't redirect. The pipermail variant has been [linked from listinfo.cgi going back to 2004](https://web.archive.org/web/20040606180635/http://lists.whatwg.org/listinfo.cgi/whatwg-whatwg.org), but both can be found in GitHub code search.
- The archives ran from 000000.html through at least 042147.html, but apparently in April 2014 all old messages were renumbered, where [old 000000.html](https://web.archive.org/web/20061010220053/http://lists.whatwg.org/pipermail/whatwg-whatwg.org/2004-April/000000.html) == [new 042273.html](https://web.archive.org/web/20140401115335/http://lists.whatwg.org/pipermail/whatwg-whatwg.org/2004-April/042273.html) and [old 042147.html](https://web.archive.org/web/20140401212025/http://lists.whatwg.org/pipermail/whatwg-whatwg.org/2014-March/042147.html) == [new 084420.html](https://web.archive.org/web/20140401144506/http://lists.whatwg.org/pipermail/whatwg-whatwg.org/2014-March/084420.html). The shift is 42273 for both pairs there, and also confirmed for a message in the middle of the range, [old 018930.html](https://web.archive.org/web/20140402050119/http://lists.whatwg.org/pipermail/whatwg-whatwg.org/2009-March/018930.html) == [new 061203.html](https://web.archive.org/web/20140401143720/http://lists.whatwg.org/pipermail/whatwg-whatwg.org/2009-March/061203.html).
- The archives go on for only a little bit after that renumbering, and [084613.html](https://web.archive.org/web/20140402033409/http://lists.whatwg.org/pipermail/whatwg-whatwg.org/2014-April/084613.html) is the latest message I can find.
- The numbering later reset again to start at >200k, twice! Only ~20 of those pages are in web.archive.org, and unfortunately some that aren't [have been linked](https://github.com/DavidBruant/coussin.js/blob/6016448214ad37cdc9d4ecf1478a19dd07fd515c/index.html#L17). The offset seems to be 169475 and 211997 for the two resets:
  - [old 044572.html](https://web.archive.org/web/20140401230608/http://lists.whatwg.org/htdig.cgi/whatwg-whatwg.org/2004-November/044572.html) + 169475 == [new 214047.html](https://web.archive.org/web/20161123141056/http://lists.whatwg.org/htdig.cgi/whatwg-whatwg.org/2004-November/214047.html)
  - [old 084390.html](https://web.archive.org/web/20140401144531/http://lists.whatwg.org/pipermail/whatwg-whatwg.org/2014-March/084390.html) + 169475 == [new 253865.html](https://web.archive.org/web/20140805113726/http://lists.whatwg.org/pipermail/whatwg-whatwg.org/2014-March/253865.html)
  - [old 044575.html](https://web.archive.org/web/20140401230731/http://lists.whatwg.org/htdig.cgi/whatwg-whatwg.org/2004-November/044575.html) + 211997 == [new 256572.html](https://web.archive.org/web/20161129143948/http://lists.whatwg.org/htdig.cgi/whatwg-whatwg.org/2004-November/256572.html)
  - [old 066533.html](https://web.archive.org/web/20140401180514/http://lists.whatwg.org/pipermail/whatwg-whatwg.org/2009-December/066533.html) + 211997 == [new 278530.html](https://web.archive.org/web/20161227172504/http://lists.whatwg.org/pipermail/whatwg-whatwg.org/2009-December/278530.html)

Based on all this it should be possible to create redirect rules or a 404 page that checks all possible URLs in web.archive.org for a match.

However, since the pre-2017 archives aren't available on lists.whatwg.org, restoring them shouldn't block turning off the mailing lists, but would be nice to get done.

**Comment by gosko** [comment]
@foolip I'm curious about this:

>     * https://lists.w3.org/Archives/Public/public-whatwg-archive/ has all of [whatwg@whatwg.org](mailto:whatwg@whatwg.org) but with different message IDs assigned, and a mapping is non-trivial

The message-ids in W3C's copy seem to be the originals, as far as I can tell.

I'm not sure if this would be useful (and maybe you already know) but W3C's archives are available in mbox format, e.g. https://lists.w3.org/Archives/Public/public-whatwg-archive/mboxes/ (restricted to W3C Members to limit bulk harvesting by spammers)

**Comment by foolip** [comment]
@gosko in that context by "message IDs" I mean the numbers in the URLs like in https://github.com/whatwg/meta/issues/153#issuecomment-566980200, not the long identifiers in `Archived-At` headers as in https://github.com/whatwg/meta/issues/153#issuecomment-566787010.

I had noticed that the mbox archives are available, and think those could come in handy for reconstructing. It's just a lot of work to do this well and with confidence in the results given that you could at best sample the results to look for problems.

**Comment by foolip** [comment]
The email lists have bee shut down now. lists.whatwg.org now has no DNS records, and I'm looking at bringing up a static copy of what I've scraped and what can still be scraped from web.archive.org.

**Comment by foolip** [comment]
lists.whatwg.org has been restored as well as it can be from web.archive.org now. If people can try using it and report issues that'd be great. Known issues:
- search doesn't work
- no redirects based on https://github.com/whatwg/meta/issues/153#issuecomment-566980200 for the  >200k resets

**Comment by foolip** [comment]
I see there's one more issue. Looking for broken links from the monthly listings, I see that May and June of 2014 don't have the individual messages:
https://lists.whatwg.org/pipermail/whatwg-whatwg.org/2014-May/thread.html
https://lists.whatwg.org/pipermail/whatwg-whatwg.org/2014-June/thread.html

https://lists.whatwg.org/pipermail/whatwg-whatwg.org/2014-May/254200.html is the only message.

These may be possible to restore from "Gzip'd Text", but I'll just link to lists.w3.org for these two months, as I've already done for July 2014 through June 2017.

**Comment by foolip** [comment]
With https://github.com/whatwg/whatwg.org/pull/285 this has bee resolved.
