### ISSUE TITLE
Add a team with Triage permission level

### ISSUE THREAD

**Issue by zcorpan** [whatwg/meta#154]
I think it would be good to give some folks (like @jugglinmike) ability to add labels to issues that they report.

https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/repository-permission-levels-for-an-organization

There's now a Triage permission level, which allows e.g. labeling and closing issues, without giving write access.

@annevk noted in IRC that the new options could also allow us to have fewer admins.

**Comment by annevk** [comment]
I created @whatwg/triage, added all 15 standard repositories, gave the team the Triage permission for those, and invited @jugglinmike.

**Comment by annevk** [comment]
I've invited a few more people and documented it in https://github.com/whatwg/meta/commit/ae961247e579dc75fe4cb591fea19bdc7cde4bad.
