### ISSUE TITLE
Participant Agreement: "Individual" vs "Entity" confusion

### ISSUE THREAD

**Issue by matteocargnelutti** [whatwg/meta#160]
Good afternoon,

I would like to get involved in WHATWG's endeavors. I have read the [Participant Agreement](https://participate.whatwg.org/agreement) sheet on whatwg.org and I am a little bit confused about the distinction between _"Individual"_ and _"Entity"_.

I work in tech as a software developer for a company, but I would like to contribute individually: is that possible?

It is not entirely clear to me as the form says:
> I represent that I do not work in the field of web technologies as an employee, contractor, or agent of another person or legal entity, and make this Agreement in my personal capacity only.

Thanks in advance,

**Comment by domenic** [comment]
It appears that you work in the field of web technologies, so, you cannot participate as an individual; you will need your employer to sign the agreement as an entity.

**Comment by matteocargnelutti** [comment]
This is what I thought, thanks for the confirmation 👍 .

**Comment by michaelcpuckett** [comment]
I am also an employed web developer who does not want to participate on behalf on my company. The W3C community group rules allow me to join as an individual if my employer has explicitly given me permission to do so.

How can I recommend a change to the rules to allow for such a participation agreement?

**Comment by sideshowbarker** [comment]
> I am also an employed web developer who does not want to participate on behalf on my company. The W3C community group rules allow me to join as an individual if my employer has explicitly given me permission to do so.
> 
> How can I recommend a change to the rules to allow for such a participation agreement?

At https://github.com/whatwg/sg/issues/62 there’s an open issue for the WHATWG Steering Group; it would be helpful if you could add a comment there.

**Comment by annevk** [comment]
Closing this in favor of that issue. Issues with the Participant Agreement are best directly taken up with the SG.

Note that https://github.com/whatwg/sg/pull/115 will take care of defining field of web technologies better.

**Comment by othermaciej** [comment]
In particular, the new definition of "work in the field of web technologies" will not include working as a web developer (though it may include some specific web developers depending on their other responsibilities).
