### ISSUE TITLE
Horizontal GitHub labels on WHATWG spec repos?

### ISSUE THREAD

**Issue by plehegar** [whatwg/meta#162]
Long story short, W3C is switching to use GitHub labels to help our horizontal groups to track their review comments:
 https://w3c.github.io/horizontal-issue-tracker/

We've been deploying those labels constantly:
  https://w3c.github.io/issue-metadata.html#horizontal-reviews

The definition of those labels comes from:
  https://w3c.github.io/hr-labels.json

Since our horizontal groups are also providing feedback to the whatwg specs, I wonder if we can deploy those labels to the whatwg spec repos as well (already the case for i18n-* labels).

For example, [3047](https://github.com/whatwg/html/pull/3047) is tracked by the privacy folks and it would be nice to add "privacy-tracker" to it.

If the labels get added, the next step to figure out will be how those labels can be added on issues when needed. Ad-hoc is good answer for now I think but open for ideas.

**Comment by annevk** [comment]
Yeah, we have similar labels but we can probably deduplicate.

1. How stable will these names be?
2. How often do we expect more labels?
3. Who should I invite for label triage? (We have a team that has the Triage permission so they can set labels on issues and such. Already used for i18n.)
4. How are symbol/longdesc/repo to be used?

Depending on 1/2 it might be nice to have more information in the JSON resource (is that a stable URL?) so https://github.com/whatwg/meta/blob/master/LABELS.md can have some links in it to the respective groups automatically. (Perhaps a Markdown version of the description.)

**Comment by annevk** [comment]
While we're here, does the W3C have an MDN story that would make sense to share? We have an "impacts documentation" label as well as a whatwg/documentation team we try to use as needed.

**Comment by plehegar** [comment]
1. I'd say the labels are pretty stable at this point and aligned among all of our horizontal groups.
2. we might get 2 more for the TAG. Nothing beyond that at this point. We are spreading labels for errata management but I think it's not relevant for the whatwg. The W3C/WHATWG MOU does mention "custom labels" but I'd say that's outside the scope of this request and would only be applicable for HTML and DOM if any.
3. I'll come back with a list of github account names for privacy, security and accessibility (and TAG?). Sounds like you're all set for i18n already. You may want to add me temporarily since I've been doing some harmonization to bring everyone up-to-speed.
4. the broad description of the labels are in the doc I pointed to. We're working on guidance for folks but here is the short version:

*-tracker should be used by anyone (whatwg folks or triage team) to bring any issue to the attention of one of our horizontal groups. Whether the horizontal group chooses to act on it or not is up to them however.

*-needs-resolution should only be used by the triage team to indicate that the horizontal group see the issue as important and expects a resolution. From our side, I'd say this is only relevant to us for the html and dom repositories given the MoU and only if the horizontal group go through the HTML Working Group if they want to escalate the matter. From the whatwg side, I guess it could help with prioritization of issues, if anything.

Issues with *-tracker and *-needs-resolution will automatically show up in the [radar](https://w3c.github.io/horizontal-issue-tracker/) after some delay. We don't automatically track a whatwg repository unless an horizontal group asks us to so far (for an example, see [i18n config](https://github.com/w3c/github-notify-ml-config/blob/master/mls.json#L345)). We could easily track more in our tooling btw (we have a github cache that preloads issues from all repositories for a given set of GH orgs, including the whatwg).

cc @dontcallmedom @r12a

**Comment by plehegar** [comment]
On MDN, having a label to help the MDN side sounds like a good idea to me, but I don't know if it helps the MDN folks. @dontcallmedom is our W3C/MDN contact so he would probably be more up to speed on that front.

**Comment by dontcallmedom** [comment]
re MDN, we don't have a clear story on this yet - part of this is that MDN is looking into transitioning their content to github, at which point the exact sync workflow will be easier to design and apply.

**Comment by plehegar** [comment]
one more point: on the JSON URL, yes, I can commit for it to be stable.

**Comment by domenic** [comment]
> we have similar labels but we can probably deduplicate.

Just popping by to note I don't see any obvious deduplications here. E.g. our `security/privacy` should not be merged with `privacy-tracker` or `privacy-needs-resolution` since those are PING-specific.

I'm a bit sad about the generic nature of these labels (i.e. using `privacy-tracker` for something PING specific) but I guess it's not a big deal. We can ameliorate it using label descriptions probably, e.g. adding a `W3C: ` prefix before the description that GitHub shows.

**Comment by annevk** [comment]
You think that PING would not want to track all privacy issues? That hasn't been a problem for i18n to date. I'd rather not have to label things twice.

**Comment by plehegar** [comment]
fyi, PING is already tracking HTML. See https://github.com/w3cping/tracking-issues/issues?q=is%3Aissue+is%3Aopen+label%3As%3Ahtml
(as a side, PING has been a lot proactive at tracking WICG repos as well btw).

It doesn't hurt to keep the security/privacy label as well btw, if the whatwg editors want to flag some issues without putting them in the PING radar. It may be that PING triage team may elect to track some of those anyway.

I do recognize that we're all struggling in resolving the privacy issues to everyone satisfaction, as I'm sure you're already aware :(

**Comment by annevk** [comment]
I put up a PR at #164 that doesn't try to do anything ambitious. It imports the upstream labels, annotates them to make it clear they are from upstream, and also writes them out in the documentation (LABELS.md) accordingly with a link to the W3C horizontal labels documentation.

**Comment by annevk** [comment]
@plehegar I've invited you to the triage team. More people can be added. Either via a new issue here, or asking Domenic / Mike / me.

**Comment by plehegar** [comment]
Nice. Fyi, we deployed our horizontal-admin, such as https://github.com/orgs/w3c/teams/horizontal-admin . We'll add a tool to keep them in sync. Here is my guideline for those in the horizontal team:
[[
You are part of the triage team since you are involved in horizontal reviews of Web specifications. This means that you may need to add a *-tracker or *-needs-resolution label on any of the issues associated one of the repositories of this team. The full triage of the issues is under the responsibilities of the Groups however so refrain from doing anything else except applying an horizontal label..

Using your participation in the triage team, You MAY only apply an horizontal label to a Group issue, ie one of the *-tracker or *-needs-resolution label.

You MAY NOT re-open an issue in a Group even if the Group chose to close an horizontal issue prematurely.
]]

If someone from the horizontal team is misbehaving, don't hesitate to bring this up.

**Comment by annevk** [comment]
Shall I invite those people to the WHATWG triage team?

**Comment by plehegar** [comment]
please do. Ideally, all of the people listed in https://github.com/orgs/w3c/teams/horizontal-admin .

I added the privacy-tracker to 2 HTML issues already.

**Comment by annevk** [comment]
Great, done.

**Comment by plehegar** [comment]
one last thing: can you rename the team to "horizontal-admin"? this would match similar teams in w3c, WICG, etc.

**Comment by domenic** [comment]
I think it's OK if different standards groups have different team names.

**Comment by annevk** [comment]
The WHATWG team also has a broader purpose. It's basically there to give people the GitHub Triage permission so they can help out with various aspects of standardization.

**Comment by plehegar** [comment]
I integrated the TAG last week as part of our horizontal review tracking. We're working on clarifying of what type of issues may be valuable for the TAG but we added the labels "tag-tracker" and "tag-resolution" (see [descrtiption](https://w3c.github.io/issue-metadata.html) and [raw definition](https://w3c.github.io/hr-labels.json)). For the horizontal team, I added @torgo, @plinss, and @ylafon. Can those labels and 3 individuals be added please?

**Comment by annevk** [comment]
https://github.com/whatwg/meta/pull/167 and added them. Please create a fresh issue next time. It's easy to forgot about already closed issues.

**Comment by plehegar** [comment]
thank you and will create a pull request next time.

**Comment by plehegar** [comment]
(actually, I don't expect a next time btw. unless I'm mistaken, we're done)
