### ISSUE TITLE
Convert labels.py to Python 3

### ISSUE THREAD

**Issue by annevk** [whatwg/meta#163]
I worked on this for a bit but `urllib` is a pain as it requires installing certificates locally? Perhaps `requests` is a way out, but none of this is a priority for me as long as this script continues working.

I can push my branch if someone is interested in taking this on.

**Comment by juliegumede** [comment]
> I worked on this for a bit but `urllib` is a pain as it requires installing certificates locally? Perhaps `requests` is a way out, but none of this is a priority for me as long as this script continues working.
> 
> I can push my branch if someone is interested in taking this on.
