### ISSUE TITLE
Main Git branch renaming across WHATWG repositories

### ISSUE THREAD

**Issue by annevk** [whatwg/meta#174]
As per https://mail.gnome.org/archives/desktop-devel-list/2019-May/msg00066.html the use of master in Git is clearly problematic.

I have some hope that GitHub will make this easier soonish (see https://twitter.com/natfriedman/status/1271253144442253312 though note that the replies are trash).

If that doesn't pan out, we can do it ourselves per the instructions in https://www.hanselman.com/blog/EasilyRenameYourGitDefaultBranchFromMasterToMain.aspx. main is also the name I'd suggest we use as there seems to be some tentative agreement around that.

Does anyone foresee any problems?

**Comment by dbaron** [comment]
One GitHub issue I'm aware of is that if a repository is using GitHub Pages, that's only possible from a branch called `master` or `gh-pages`.  So if any are, they'd probably need their primary branch renamed to `gh-pages` instead of `main`, at least for now.  I saw a tweet about 6-12 hours ago saying they're working on fixing that, but I can't find it again.

I think another is that the step to update the default branch in [the article you cite](https://www.hanselman.com/blog/EasilyRenameYourGitDefaultBranchFromMasterToMain.aspx) causes GitHub to give a big red warning box saying it might break certain things; I don't remember the contents of the warning but I think one of them was currently-outstanding pull requests.  Another might be clones that people have.  Given the convention about maintaining relatively long-lived PRs, that might be a bit problematic, and it's probably worth seeing how bad the effects will be with a test in another repository...

**Comment by zcorpan** [comment]
I saw this, which might be helpful: https://github.com/mheap/github-default-branch (via https://twitter.com/mheap/status/1272277332783497218?s=20 )

**Comment by foolip** [comment]
I tried renaming the default branch on a personal repository today to see what I'd run into:
- Created and pushed the main branch
- Pushed an additional commit to the main branch [fixing CI setup](https://github.com/foolip/day-to-day/commit/806daf8abc2af564d39c494f330584d14be382fc)
- Changed the branch protection rules to apply to the main branch
- Changed the default branch in GitHub's settings
  - This step automatically changed the base branch of the single open PR, a nice surprise
- Removed the master branch

This all is not hard to do across all of our repos.

However, the final step of removing the master branch is going to break URLs, and there are probably quite many. I filed https://github.com/mheap/github-default-branch/issues/6 about this, but don't know a good solution. The least bad option I can see is to add a final commit to the master branch with an ALL CAPS commit message and changing the README or another file that's unlikely to be linked, explaining the situation. The branch would need to be left around in perpetuity.

To solve this well, GitHub-side handling of branch renaming by redirecting would be needed.

Something I haven't explored is what happens to local checkouts. This too won't be entirely smooth unless there's GitHub-side handling, some kind of aliasing.

**Comment by domenic** [comment]
> To solve this well, GitHub-side handling of branch renaming by redirecting would be needed.

I am hopeful this is in the works, given [a vague public statements from the GitHub CEO](https://twitter.com/natfriedman/status/1271253144442253312) on Twitter. So we should probably hold off to see what they announce.

**Comment by zcorpan** [comment]
https://github.com/chancancode/branch-rename might also be helpful.

I agree that waiting for GitHub is reasonable, but we can also inform them about the redirect feature request. Is [Contact GitHub](https://github.com/contact) the right venue?

**Comment by foolip** [comment]
Yeah, use that form. I tried to email support@github.com a few days ago (about something else) and that doesn't work. Unlike what I've seen people claim, I've found GitHub's support to be pretty great, just not always fast.

**Comment by zcorpan** [comment]
Done, I've sent this:
```
See https://github.com/whatwg/meta/issues/174#issuecomment-644423829

> To solve this well, GitHub-side handling of branch renaming by redirecting would be needed.

Also see https://github.com/mheap/github-default-branch/issues/6

Can GitHub provide a way to redirect URLs when renaming branches?
```

**Comment by zcorpan** [comment]
> Hello Simon,
>
> Thanks for writing in! We are actively working alongside the Git project itself, as well as other version control vendors, on making three changes in GitHub: (1) we are changing the default branch name for new repos away from ‘master’ (2) we are making it easy for users to choose their own default branch name for all new repos created (3) we are releasing guidance and tools for users who may choose to rename their default branch in existing repos.
>
> Our Pages team is also exploring ways to resolve the issue of the limited branch options in Pages sources.
>
> I'm afraid I can't provide more concrete details yet, but thank you for writing in with this feedback. I am going to pass along your suggestion of redirecting URLs to our Product team, as that would certainly fall under number 2 above.

**Comment by annevk** [comment]
You might want to point out that it falls under 3.

**Comment by foolip** [comment]
https://github.com/google/mirror-branch-action by @jyasskin is something we could consider here, and fairly trivial to roll out using https://github.com/whatwg/spec-factory. Or we bake something into our deploy scripts to avoid using extra CI resources for this.

My only hesitation is that by maintaining the branch like this, "master" will keep showing up in `git fetch` and `git log --decorate` output indefinitely, so it'll still be there staring maintainers and contributors in the face every day.

Has anyone heard any updates on what GitHub might be planning here?

**Comment by travisleithead** [comment]
No, I haven't heard anything yet.

**Comment by mheap** [comment]
Good news! GitHub have just announced that any deleted branches now redirect to the default branch https://github.blog/changelog/2020-07-17-links-to-deleted-branches-now-redirect-to-the-default-branch/

**Comment by annevk** [comment]
Note that later in the year this will be a mostly automated process: https://github.com/github/renaming.

**Comment by foolip** [comment]
https://github.com/github/renaming#later-this-year-seamless-move-for-existing-repositories- looks promising, but I don't see anything about preserving URLs. All the rest we could do ourselves now, but redirecting URLs we cannot.

**Comment by foolip** [comment]
https://github.blog/changelog/2020-07-17-links-to-deleted-branches-now-redirect-to-the-default-branch/ is excellent!

https://github.com/github/renaming#later-this-year-seamless-move-for-existing-repositories- looks like it will add some convenience, but I think most of the work for us would be in adapting our CI setup and updating references to master in lots of little places.

In other words, I don't think we necessarily need to wait for more support in https://github.com/github/renaming.

**Comment by annevk** [comment]
I looked into this again and per https://github.com/github/renaming#creating-a-seamless-move-for-existing-repositories- we should be able to roll this out soon. I suspect there will be some announcement in the coming weeks and when that comes we can start with the transition.

When that time comes we should grep for `master` as we do have code, e.g., https://github.com/whatwg/meta/blob/master/review.py, that relies on that. Some of that might continue to work as a result of GitHub making things more seamless, but we should still clean it up. Given that there are cross-repository dependencies we probably need to do it all in one sweep. Once GitHub makes the announcement I'm happy to start preparing PRs for the changes we need to make to code and such. And I guess I can work with @foolip (if he agrees) on doing the renaming and ensuring things work as expected afterward.

If anyone has other things we should consider now would be a good time to voice them.

**Comment by annevk** [comment]
There's two kinds of changes we need to make. For all repositories we need to flip the branch name. We can also do this for archived repositories by unarchiving them, changing it, then archiving them again. (I have not listed those for now, but I'd like to do that as well once the main work is done.)

Here are the repositories in a list, I've already flipped some that I deemed safe:

- [x] books
- [ ] compat
- [ ] console
- [ ] dom
- [ ] encoding
- [ ] fetch
- [x] figures
- [ ] fullscreen
- [ ] html
- [ ] html-build
- [ ] infra
- [x] loader
- [ ] meta
- [ ] mimesniff
- [ ] misc-server
- [ ] notifications
- [ ] participant-data
- [ ] participate.whatwg.org
- [x] platform.html5.org
- [ ] quirks
- [ ] sg
- [x] spec-factory
- [ ] storage
- [ ] streams
- [ ] url
- [ ] wattsi
- [x] web-history
- [ ] whatwg.org
- [ ] xhr

Then we need to make code changes to account for the branch name changes, let's track those in this list (known to be incomplete):

- [ ] https://github.com/whatwg/compat/pull/139
- [ ] https://github.com/whatwg/console/pull/192
- [ ] https://github.com/whatwg/html/pull/6285
- [ ] https://github.com/whatwg/meta/pull/197
- [ ] https://github.com/whatwg/sg/pull/151
- [ ] https://github.com/whatwg/spec-factory/pull/25
- [ ] https://github.com/whatwg/whatwg.org/pull/349

**Comment by domenic** [comment]
As pointed out in https://github.com/whatwg/streams/pull/1101#issuecomment-759772853, the grepping for "master" does not seem to be complete, i.e. it seems to have missed all the GitHub Actions code.

**Comment by annevk** [comment]
This is now done, including for archived repositories. To avoid the mistake I almost made for your own projects, use

> `grep -r master * .* --exclude-dir={..,.,.git}`

or equivalent.

Pull requests will need to be rebased unfortunately due to the build configuration files including the default branch name. Let me know if you encounter problems.

The only weirdness I encountered thus far has been https://github.com/domenic/wattsi-server/issues/13, but it's unclear if that was related to the rename.

Thanks everyone!

**Comment by Dfhjbcccc** [comment]
> As per https://mail.gnome.org/archives/desktop-devel-list/2019-May/msg00066.html the use of master in Git is clearly problematic.
> 
> I have some hope that GitHub will make this easier soonish (see https://twitter.com/natfriedman/status/1271253144442253312 though note that the replies are trash).
> 
> If that doesn't pan out, we can do it ourselves per the instructions in https://www.hanselman.com/blog/EasilyRenameYourGitDefaultBranchFromMasterToMain.aspx. main is also the name I'd suggest we use as there seems to be some tentative agreement around that.
> 
> Does anyone foresee any problems?

А
