### ISSUE TITLE
COMMITTING.md: line length for title or also for body

### ISSUE THREAD

**Issue by annevk** [whatwg/meta#177]
Is the line length limit only for commit titles or also for the body? I hope only for the title as it would be a bit of a pain to format the body accordingly in a textarea when using squash & commit. If indeed it also applies to body we need to change the examples and I guess figure out a way to usefully enforce it.

**Comment by foolip** [comment]
As a matter of convention in whatwg/html, it looks like at least @domenic and @TimothyGu  wraps body at 72, and it's easy to find others also wrapping at some level. Skimming, it looks like most long line numbers are @annevk, but not exclusively.

**Comment by ricea** [comment]
I wrap at 72, but GitHub certainly doesn't make it easy.
