### ISSUE TITLE
Make it more obvious how to close commit-snapshot dialog

### ISSUE THREAD

**Issue by annevk** [whatwg/meta#18]
Since we use this all over now (including HTML diffs), we should make it more obvious how to close it. Perhaps just render an [X] in the top? Or "click here to close"?

**Comment by domenic** [comment]
An [X] sounds pretty good. I wonder if we can do it purely through CSS (I doubt it).

**Comment by zcorpan** [comment]
Doing it with CSS generated content is easy. Question is what should it say.

* ❎ ("ex mark" in VO)
* ❌ ("cross mark" in VO)
* OK
* Close

**Comment by annevk** [comment]
Maybe "collapse" and "expand" (for when it's collapsed)?
