### ISSUE TITLE
Add more i18n labels

### ISSUE THREAD

**Issue by xfq** [whatwg/meta#182]
The W3C i18n WG uses a set of labels for tracking issues in W3C groups (WG/CG/IG etc.) and the WHATWG. (See some examples in [CSS](https://github.com/w3c/csswg-drafts/labels?q=i18n), [HTML](https://github.com/whatwg/html/labels?q=i18n), [Web Audio API](https://github.com/WebAudio/web-audio-api), [WebAssembly](https://github.com/WebAssembly/spec/labels?q=i18n), [WebXR](https://github.com/immersive-web/webxr/labels?q=i18n), and [MathML](https://github.com/mathml-refresh/mathml/labels?q=i18n).)

The labels include a `i18n-tracker` label, a `i18n-needs-resolution` label (documented [here](https://www.w3.org/wiki/DocumentReview#Working_with_Horizontal_Review_Labels)), and a few `i18n-*lreq` labels. The effect of the `i18n-*lreq` labels is to notify experts in the language enablement groups (such as [clreq](https://github.com/w3c/clreq/) and [jlreq](https://github.com/w3c/jlreq/)) on activities in the issues with these labels.

The HTML repo currently doesn't have the following labels:

* `i18n-eurlreq`
* `i18n-mlreq`
* `i18n-sealreq`
* `i18n-tlreq`
* `i18n-afrlreq`
* `i18n-elreq`
* `i18n-amlreq`

Maybe not all of them are useful for current issues in HTML, but according to https://github.com/whatwg/html/issues/5121 , I think at least these two labels are needed for that issue:

* `i18n-mlreq` (for Mongolian)
* `i18n-amlreq` (for American languages)

I can submit a pull request against [LABELS.md](https://github.com/whatwg/meta/blob/master/LABELS.md) and [labels.json](https://github.com/whatwg/meta/blob/master/labels.json), if it does not require my employer to sign the participation agreement.

**Comment by annevk** [comment]
It does not require that and it'd be appreciated. I updated `labels.py` in #184 to make rolling this out a bit easier.
