### ISSUE TITLE
Port HTML build regular expressions to shared build script?

### ISSUE THREAD

**Issue by annevk** [whatwg/meta#19]
Given things like https://github.com/whatwg/url/pull/249 that might be nice. It would also give us consistent spelling practices across standards.

@zcorpan something you might be interested in?

**Comment by zcorpan** [comment]
Maybe but don't feel I have the bandwidth to do it at the moment, so if someone else want to pick it up that's entirely cool.

**Comment by annevk** [comment]
This is https://github.com/whatwg/whatwg.org/issues/66 now.
