### ISSUE TITLE
Consider advertising the commit feed in the bio of the Twitter accounts

### ISSUE THREAD

**Issue by simevidas** [whatwg/meta#198]
[Your Twitter account has started tweeting commits again.](https://twitter.com/domenic/status/1355238938701664257)

People who encounter these tweets may want to subscribe to the RSS feed instead but may not know that one exists. GitHub automatically provides feeds for commits. Yours is

    https://github.com/whatwg/html/commits/main.atom

If you added this URL to the bio of your Twitter account, more people would become aware of this option, and more people would potentially subscribe to your commits.

An example of promoting a URL in the bio:

<img width="846" alt="Screen Shot 2021-01-30 at 6 57 46 AM" src="https://user-images.githubusercontent.com/716405/106348742-c26f7e00-62c8-11eb-84b7-4f8ffc47eec4.png">

**Comment by annevk** [comment]
I've done this for `@htmlstandard` to see what it would look like. I've called it "RSS feed" as I guess that's what it's known by, for better or worse.

We could roll this out more generally to all Twitter accounts or we could link other things I suppose, e.g., a link to https://github.com/whatwg/html/commits.

**Comment by domenic** [comment]
I'd like us to revert this change. I think it clutters the bio with "non-biographical" information that isn't of interest to most people. It also is a poor experience on mobile (where .atom files trigger a download).

Ultimately, I think people who are using Twitter to get notifications of commits are unlikely to benefit from RSS. And people who are interested anyway, will know about this feature for any repository on GitHub; it's not our responsibility to advertise it.

**Comment by simevidas** [comment]
> I think people who are using Twitter to get notifications of commits are unlikely to benefit from RSS.

That may be true, but the bio is accessible to non-subscribers as well.

I think a common scenario is that one of the tweets gets re-tweeted a bunch of times, leading to a bunch of people finding out that the HTML Standard has a Twitter account. Some of these people will check out the Twitter account, and then read the bio and decide if they want to subscribe, either via RSS or on Twitter.

So I view the RSS link in the bio as an alternative option for people who haven’t yet subscribed on Twitter. It’s like when you discover a Twitter account that shares interesting videos, and then you check out the account and find a link to their YouTube channel in the bio, so you subscribe on YouTube instead. Giving people more options is good.

> And people who are interested anyway, will know about this feature for any repository on GitHub.

I wouldn’t be so sure about that. I maintain the biggest collection of feeds for web developers (https://github.com/simevidas/web-dev-feeds), and yet I didn’t know for a long time that GitHub provides feeds.

**Comment by domenic** [comment]
In the end I don't think it's our responsibility to surface this GitHub feature, and it distracts from the intentionally Twitter-centric nature of the Twitter channels.

**Comment by annevk** [comment]
I've reverted this. With one being supportive and one opposed I guess the status quo wins. (I'm somewhat ambivalent myself.)
