### ISSUE TITLE
Landing PRs quickly after each other can cause problems

### ISSUE THREAD

**Issue by annevk** [whatwg/meta#20]
In particular an older commit on master might take a longer time building and by the time it finishes, overwrite the newer commit that was already copied to the server. This happened with Fetch today (the ABNF change is no longer represented until I land another commit).

**Comment by annevk** [comment]
Okay, so this is basically https://github.com/travis-ci/travis-ci/issues/6547. There's two intermediate solutions:

1. Disable concurrency for each repository.
2. Avoid landing PRs on master too quickly after each other.

I don't think there's a huge drawback with 1, but would like to hear from @domenic and @foolip at least.

**Comment by foolip** [comment]
Are there cases where you'd want commit snapshots for both commits? If not then I think just disabling concurrent builds is the way to go.

**Comment by annevk** [comment]
I would like that. I was hoping disabling concurrent builds would just mean they'd run consecutively.

**Comment by foolip** [comment]
Unfortunately that isn't the case. The only other option I see would be to check before deploy of / (but not snapshot) if master is already pointing at a later commit, and then so nothing. A bit of complexity added.

**Comment by annevk** [comment]
This isn't a big problem in practice as far as I can tell so I'm going to close this.
