### ISSUE TITLE
participate.whatwg.org still links to IRC

### ISSUE THREAD

**Issue by equalsJeffH** [whatwg/meta#217]
https://participate.whatwg.org/  links to https://whatwg.org/irc

https://participate.whatwg.org/  ought to link to https://whatwg.org/chat

https://whatwg.org/irc perhaps should go away since https://whatwg.org/chat links to the IRC archives?

**Comment by annevk** [comment]
Thanks! Created https://github.com/whatwg/participate.whatwg.org/pull/216.

For the latter problem I suspect we need to invalidate the service worker cache to account for the redirect. @domenic should we update https://resources.whatwg.org/website-service-worker.js or add `self.cacheKey` to https://whatwg.org/service-worker.js?

**Comment by domenic** [comment]
We should add `self.cacheKey`.

**Comment by annevk** [comment]
Once the service worker updates locally and you hit refresh it'll redirect now. https://participate.whatwg.org/ is updated too. Thanks again!
