### ISSUE TITLE
accessibility of select lists

### ISSUE THREAD

**Issue by RichCaloggero** [whatwg/meta#229]
Firstly, I am a blind screen reader user doing accessibility testing / QA for a large university.  

One of the most persistent issues I find in both my professional work and personal experience with countless websites is the need to code custom list boxes using aria and homegrone (usually faulty) keyboard behavior. From what little visual understanding I have, this is because standard HTML does not allow select lists to be styled in a way that meets the needs of most sighted individuals. It also comes from the need to use images and other complex elements in these type of controls, which is not supported by standard HTML.

Is there a reason why these type of controls cannot be part of the spec, and why they cannot be styled as flexably as other controls?  If such controls existed, much wasted time and poorly coded custom controls could be potentially eliminated.

**Comment by annevk** [comment]
The Open UI effort is looking into this: https://open-ui.org/.
