### ISSUE TITLE
Document and unify labels and colors

### ISSUE THREAD

**Issue by domenic** [whatwg/meta#25]
HTML has a pretty good set of labels. We've copied some of them to other specs but not all. It might be nice to do so, and document them. (Although, the topic: labels should be per-spec, I think... although certain topics like custom elements cross specs.)

https://www.google.com.sg/search?q=github+label+sync shows that there are lots of tools to help with this.

**Comment by snuggs** [comment]
@domenic would you happen to have a list of the existing repos that need to be included in the ontology? Perhaps a ven diagram output is a nice Picasso of course after addressing a good base stick figure.

P.S. I concur label syncing is 🔑

**Comment by annevk** [comment]
We made some progress here: #42, #44, and #63. No progress on tooling though.

**Comment by annevk** [comment]
We now have pretty good tooling with #94. We could even add it to Travis if we wanted to.
