### ISSUE TITLE
Should compost-tweet.js and review.py commit prefix checking be case sensitive?

### ISSUE THREAD

**Issue by miketaylr** [whatwg/meta#251]
Over in https://github.com/whatwg/compat/pull/203#issuecomment-1169676250 @annevk correctly pointed out that my "meta: " commit prefix didn't conform to the tooling and process expecting "Meta:" 

(@karlcow made that more clear in https://github.com/whatwg/meta/pull/250 - thx).

The only other instance I could find of a lowercase commit prefix was in https://github.com/whatwg/compat/commit/4aa38ed5a82798d6074fbe293605c118ef855d86 - also in compat (🙈).

My question is: are folks OK with a PR to make the tools understand case insensitive commit prefixes? 

It seems like the places to update would be:

https://github.com/whatwg/meta/blob/main/review.py#L60
https://github.com/whatwg/participate.whatwg.org/blob/main/lib/compose-tweet.js#L5

It's not the end of the world if the answer is "no" - but it seems like a fairly simple fix for any future mistakes.

**Comment by karlcow** [comment]
ok done two PRs. 
can be thrown. 
can be added. :) 

@miketaylr Another way to fix it for the compat spec is to create a GitHub action check on PRs in the compat repo.

**Comment by miketaylr** [comment]
> Another way to fix it for the compat spec is to create a GitHub action check on PRs in the compat repo.

Yeah, that's true. But it seems better to be consistent everywhere (and Compat is the odd-one-out, so maybe the solution is just "be more consistent, Compat").

**Comment by annevk** [comment]
I think the discussion on Chat ended up agreeing with @miketaylr's solution. I hope that's acceptable to everyone involved.

I also hope that eventually GitHub will have better tooling around commit messages so we can be as peculiar about those as we are about other aspects of our standards.
