### ISSUE TITLE
Update validator.whatwg.org

### ISSUE THREAD

**Issue by xfq** [whatwg/meta#27]
* checker.html5.org is more up to date than html5.validator.nu;
* onlinewebcheck.com was discontinued.

**Comment by annevk** [comment]
@Hixie I think only you have access to this domain at this point.

**Comment by xfq** [comment]
See also: whatwg/whatwg.org#31

**Comment by zcorpan** [comment]
Ah, this issue was here, didn't find it and thought maybe it was just on IRC. We can close this when @Hixie has made the domain point to the new location.

**Comment by annevk** [comment]
So this should just redirect 301 to https://whatwg.org/validator/ at this point?

**Comment by domenic** [comment]
I think the idea was to make it like spec.whatwg.org; see https://github.com/whatwg/whatwg.org/blob/1aa58f57314ba55c72c026d76b41c8bfbbb4e0f5/src/validator/index.html#L2

**Comment by annevk** [comment]
I see, so then once this is fixed that way we would need to redirect the link I pasted above to validator.whatwg.org instead.

**Comment by domenic** [comment]
At this point it seems to have become a redirect to https://whatwg.org/validator/; good enough I guess.

**Comment by xfq** [comment]
Thanks!
