### ISSUE TITLE
Moar labels

### ISSUE THREAD

**Issue by annevk** [whatwg/meta#270]
Some labels from HTML I find myself wishing for from time to time:

* integration
* spam
* meta

Anything else?

**Comment by annevk** [comment]
As @zcorpan mentioned "good first issue" has become useless. Maybe we should remove "good first issue".

**Comment by zcorpan** [comment]
Yeah. Maybe we can move the text

> We'd be happy to mentor you through this process. If you're interested and need help getting started, leave a comment on the issue or bug, or [ask around](https://whatwg.org/chat). The [FAQ](https://github.com/whatwg/html/blob/main/FAQ.md) may also be helpful.

from whatwg/html CONTRIBUTING.md to whatwg/meta CONTRIBUTING.md?

**Comment by annevk** [comment]
Yeah, although we should tell people to join Matrix if they want help from a person. Issue and PR comments are too noisy as it is.

**Comment by annevk** [comment]
"needs PR" or "awaiting PR" (as per whatwg/sg) would be good to have too.

**Comment by annevk** [comment]
Reflecting on this:

- integration still seems reasonable
- spam is now invalid
- meta still seems reasonable
- needs PR is needs concrete proposal

Not sure what to do about "good first issue". I still see people attempt to use it.

**Comment by annevk** [comment]
Seems meta was already added.
