### ISSUE TITLE
whattweetbot suspended

### ISSUE THREAD

**Issue by annevk** [whatwg/meta#274]
WHATWG admins got this email:

> Hello,
>
> This is a notice that your app - whattweetbot - has been suspended from accessing the Twitter API. However, you can self-serve reactivate your app for free.
>
> Please take the following steps to get your app quickly running again on the new Free or Basic plans available at developer.twitter.com:
>
> 1. Subscribe to either Free or Basic via [our website](https://developer.twitter.com/en).
> 2. When signing up, you will be able to pick 1 (Free) or 2 (Basic) apps that you want to remain active. They will be reactivated automatically after you complete your sign-up.
> 3. Please update the code in your app to use v2 endpoints - this is valid to all endpoints except for media upload endpoints which are not currently supported on v2 so you can continue to use those on v1.1.
>
> We apologize for any inconveniences this transition might have caused. By following these steps, you can continue to seamlessly use the Twitter API.
>
> For more information, please refer to our [developer community forums](https://twittercommunity.com/).
>
> Regards, 
> Twitter Developer Platform

I'm not interested in trying to sort this out. If someone is let me know.

If nobody steps forward we should probably deactivate https://github.com/whatwg/participate.whatwg.org/blob/main/lib/tweet-webhook.js.

**Comment by domenic** [comment]
The only part of this that seems hard is making the code changes to use the v2 API. Currently we're using the `twitter-lite` npm package to handle the OAuth stuff. (The actual POST request part is trivial and doesn't really need a package.) That doesn't seem to have been updated yet; https://github.com/draftbit/twitter-lite/issues/186 has some discussion on workarounds and PRs.

https://www.npmjs.com/search?q=twitter%20v2 has some alternatives we could try to drop in.
