### ISSUE TITLE
Circular Twitter icons?

### ISSUE THREAD

**Issue by domenic** [whatwg/meta#28]
Twitter has made everyone's icons a circle, and this looks pretty bad for a few of our spec accounts:

- https://twitter.com/storagestandard
- https://twitter.com/compatstandard
- https://twitter.com/fullscreenapi
- https://twitter.com/mimesniff

What should we do?

Unfortunately the new Twitter UI does not allow you to "zoom out" when uploading a photo; we'd need to actually produce new resources with the extra whitespace on the sides.

**Comment by GPHemsley** [comment]
Maybe if we wait long enough they're realize their mistake?

**Comment by domenic** [comment]
I dunno, it seems like popular brands have adapted, e.g. https://twitter.com/microsoft; so I doubt they're going to roll it back.

**Comment by annevk** [comment]
What Microsoft did seems reasonable.

**Comment by sideshowbarker** [comment]
Personally I like the current kind of “circular window” view into the icons at https://twitter.com/storagestandard and https://twitter.com/compatstandard and https://twitter.com/fullscreenapi a lott better than the look with all the unnecessary extra whitespace at https://twitter.com/microsoft

The current look at https://twitter.com/mimesniff is kind of the worst of both worlds but maybe that’s more a problem with the design of that icon itself more than anything else

**Comment by snuggs** [comment]
@annevk @domenic @sideshowbarker FWIW should have some updates shortly. Reached out to one of my colleagues that did NYC.rb for us.

![image](https://user-images.githubusercontent.com/38223/30767630-1be3cd88-9fb3-11e7-9b69-3d7219a00eed.png)

 We discussed taking into consideration M$ and other references.

@GPHemsley LOLz

**Comment by Antleonardo** [comment]
@snuggs asked me to help out here. I resized the logos and they should work. Give them a try and if need be I can tweak them further.

**Comment by Antleonardo** [comment]
http://www.leonardostudio.com/092219_WHATWG/

**Comment by snuggs** [comment]
Lookin' good @Antleonardo !

![capture d ecran 2017-09-22 a 16 51 17](https://user-images.githubusercontent.com/38223/30767924-4f74089a-9fb6-11e7-951f-c9992397925e.png)

**Comment by snuggs** [comment]
#butter 

![capture d ecran 2017-09-22 a 16 58 32](https://user-images.githubusercontent.com/38223/30768031-4da4a528-9fb7-11e7-9b8d-34b3bb1f8796.png)

**Comment by Antleonardo** [comment]
tweaked it to show them with twitter's style sheets

**Comment by domenic** [comment]
Thanks @Antleonardo! However, it seems there's some kidn of color profile in the images, or something, which is causing the colors to be off. They should be #3c790a. They're also a little bit fuzzy; e.g. mimesniff.png does not have straight edges anymore.

**Comment by domenic** [comment]
Hmm, I guess the color issue is preexisting; very strange...

**Comment by domenic** [comment]
Fixing png version colors at https://github.com/whatwg/whatwg.org/pull/95

**Comment by Antleonardo** [comment]
Do you have the original files? There could be some kind of image processing going on with the images after they are uploaded to twitter which is affecting the image quality and/or the profiles. If you can supply the highest res originals you have I can adjust them for the circular crop and get them to look their best.

**Comment by domenic** [comment]
The original files are the SVG ones at https://resources.whatwg.org/

**Comment by Antleonardo** [comment]
Updated images, should be more consistent and sharper.  http://www.leonardostudio.com/092219_WHATWG/index.html?new=forceRefresh

**Comment by Antleonardo** [comment]
Updated again for better cropping: http://www.leonardostudio.com/092219_WHATWG/index.html?new=forceRefresh2

**Comment by domenic** [comment]
Awesome! I updated storage and mimesniff. @annevk it asks me for the email when trying to update fullscreen (appears to be your email). Also not sure how to get acccess to compatstandard.

**Comment by snuggs** [comment]
I'm with @annevk... getting to the point my reptilian brain can't even tell the difference. As long as @domenic is happy I trust moving in a right direction. @Antleonardo thanks for helping champion this one. :clinking_glasses:

**Comment by annevk** [comment]
@domenic I added the email for fullscreenapi so you should be able to access that now. I will send email with regards to compat.

Should we host these circular images somewhere as well?

**Comment by Antleonardo** [comment]
The circularity is due to CSS style sheet, the actual images are still square.

**Comment by miketaylr** [comment]
> I will send email with regards to compat.

Just replied to you @annevk.

**Comment by domenic** [comment]
All done, yay!! Thanks very much @Antleonardo!

**Comment by snuggs** [comment]
YAY @domenic @Antleonardo @annevk !!! Glad we could get this sorted out!

**Comment by Antleonardo** [comment]
You're welcome @domenic @annevk, glad I could help out. Let me know if you need anything else.
