### ISSUE TITLE
Valid email address 

### ISSUE THREAD

**Issue by adyen-martinhagedoorn** [whatwg/meta#29]
I am using jQuery validation for validating an e-mail address.
And I saw they reference the regex from this url: https://html.spec.whatwg.org/multipage/input.html#valid-e-mail-address

The following JavaScript- and Perl-compatible regular expression is an implementation of the above definition.
/^[a-zA-Z0-9.!#$%&'*+\/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$/

I tested this regex and it seems to be incorrect. Since it also matches bla@bla in this situation.
Also the 61 should be 62? Since the DNS allows 63 characters?

Perhaps you could use this one: http://emailregex.com/
/^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/

**Comment by domenic** [comment]
Hey, I think this is better reported as an issue on the spec you are citing, the HTML Standard: https://github.com/whatwg/html

However, also see https://github.com/whatwg/html/issues?q=is%3Aissue+email+regex+is%3Aclosed, as at least some of this might have been discussed before. (Feel free to comment in closed issues; they are still monitored.)

As such let me close this meta issue, but don't take that as a sign that we're not interested in helping! Just trying to route things to the right place.
