### ISSUE TITLE
Need better workmode onboarding

### ISSUE THREAD

**Issue by cwilso** [whatwg/meta#296]
(From suggestion by Mu-An at WHATUP)

We should ensure that feature drivers have clear pointers to the workmode, and then when/if we add the Spec Acceptance Stages that we inform feature developers of this new tool to help manage expectations.

**Comment by annevk** [comment]
Thinking of what categories we want people to have templates for:

* New Feature
   * This would add addition/proposal and needs implementer interest as labels.
   * This would remind people of the FAQ, Working Mode, and Code of Conduct.
   * This would questions along the lines of "What problem are you trying to solve?" and "How would you solve it?".
   * It would direct people to Chat for questions.
* Bug
   * This would remind people of the Code of Conduct.
   * It would direct people to Chat for questions.
* Security bug (not needed for v1, but at some point we need this)

Thoughts?

**Comment by keithamus** [comment]
Would it be worth adding a template for implementer clarifications, that we might prioritise them differently (as they're likely coming from an implementer midway through work)?

**Comment by annevk** [comment]
We should probably categorize those better when triaging, but I'm not sure it helps the flow for new contributors as they might not know the difference between the various options we could offer.

I put an initial sketch up at https://github.com/annevk/temp-whatwg-new-issue/issues/new/choose (URL will disappear at some point).

**Comment by annevk** [comment]
This has now been deployed on https://github.com/whatwg/url/issues/new/choose. https://github.com/whatwg/url/#readme is also somewhat new. I'll be rolling that out to the other standards soon.

**Comment by annevk** [comment]
Remaining:

- [ ] https://github.com/whatwg/compat/pull/247
- [ ] https://github.com/whatwg/html/pull/9802
- [ ] https://github.com/whatwg/quirks/pull/72
- [ ] https://github.com/whatwg/streams/pull/1295

As noted in https://github.com/whatwg/spec-factory/issues/3#issuecomment-1736852570 there's a couple standards that need improved README's still. We could either do them manually or attempt to make them work better with spec-factory. I don't think this blocks closing this issue.

#297 tracks the remaining Stages work. I don't think that blocks closing this issue either.

**Comment by annevk** [comment]
All the issue templates have landed. See the above comment for README and Stages improvement tracking issues.

**Comment by Lishkk** [comment]
> "The PR template is nice, but we should have an issue template that points to the Working Mode"
