### ISSUE TITLE
Adding service workers to specs

### ISSUE THREAD

**Issue by domenic** [whatwg/meta#3]
Specs to add service worker to:

Special:
- [ ] HTML

Easy:
- [x] Infra
- [x] DOM
- [x] Fullscreen
- [x] Notifications
- [x] Fetch
- [x] MIME Sniffing
- [x] XMLHttpRequest
- [x] Storage
- [x] Quirks Mode

Need to start using the deploy script first (#11):

- [x] URL
- [x] Encoding
- [x] Compatibility
- [x] Console
- [x] Streams (has one, but it's a one-off created for streams)

The best path here might be to fix #11, then add the service worker registration to the Bikeshed template, instead of doing individual PRs like https://github.com/whatwg/dom/pull/476

---

_Original post follows:_

I did this for streams with some success in https://github.com/whatwg/streams/pull/637. Some thoughts:

- Maybe we should work to implement the more complicated strategy discussed at https://github.com/whatwg/streams/pull/637#issuecomment-270391258 before rolling this out everywhere?
- Is there any way to deduplicate the code? Given that it has to be hosted on the same origin, it seems unlikely. Hmm, I guess importScripts works cross-origin? So then we'd just reduce the actual in-spec code to something like `self.toCache = ...` or maybe we could even get rid of that by inferring the logo filename from the origin.

**Comment by jakearchibald** [comment]
Brain fart: The cache could be built dynamically.

Eg, the cache name could be `spec-` plus the html url, plus the etag/last-modified of the html responses. Resources fetched from that page (images & js) would be added to a cache of the same name.

Once a new version of the spec is discovered, the old cache is deleted.

It's not as atomic as handling everything in install/activate events but it could work for simple pages like specs.

**Comment by domenic** [comment]
This was deployed successfully for whatwg/dom in https://github.com/whatwg/dom/pull/476.

I'll update the OP with a checklist. Note that resources apart from the default set won't be cacheable without more deploy script work in the vein of #11.

**Comment by domenic** [comment]
This was done for everything but HTML as part of https://github.com/whatwg/meta/issues/23. (As noted there, Encoding is currently blocked; see https://github.com/whatwg/encoding/pull/132.)

We'll leave this open to track HTML though.

**Comment by annevk** [comment]
Now that Encoding is done, maybe this should move to html-build or html directly?

**Comment by annevk** [comment]
https://github.com/whatwg/html-build/issues/238
