### ISSUE TITLE
Create CODE_OF_CONDUCT.md for each repository?

### ISSUE THREAD

**Issue by annevk** [whatwg/meta#30]
It seems there might be some GitHub integration benefits to this? It shows up under https://github.com/whatwg/meta/community at least.

**Comment by domenic** [comment]
It would just be a link to the canonical one? Hmm. I'd like to hear more about the GitHub integration benefits, or if any users would find this useful compared to having it in the readme (which IMO is more obvious).

**Comment by annevk** [comment]
I can't really find any benefits so I guess I'll just close this again.
