### ISSUE TITLE
Bug: Posible Memory Leak on html.spec.whatwg.org

### ISSUE THREAD

**Issue by DmACKGL** [whatwg/meta#309]
Hi,

Vercel Docs (unrelated, for context) has a link explaining Interactive Content which redirects to https://html.spec.whatwg.org/#interactive-content-2

If you keep the tab open, Chrome has difficulty loading the site, the RAM usage spikes and the browser freezes.

![Screenshot 2024-01-15 143052](https://github.com/whatwg/meta/assets/10565361/d274f9dc-d01f-469e-a5de-26902067178b)

**Comment by annevk** [comment]
You mean you can't get it to load at all? Or that after multiple days RAM usage for that tab goes up? It's not a small document so it's somewhat expected it takes a bit of time and space.
