### ISSUE TITLE
Updates for triage team

### ISSUE THREAD

**Issue by plehegar** [whatwg/meta#312]
People to be added:
 * [ruoxiran](https://github.com/orgs/w3c/people/ruoxiran)
 
People who may be removed:
* [Samuel Weiler](https://github.com/samuelweiler)

In addition, following [comment in #223](https://github.com/whatwg/meta/issues/223#issuecomment-937513051), we changed the behavior of our definitions for labels. It's now at https://w3c.github.io/common-labels.json , but ONLY the labels that have a repo property are relevant in the context of triage. Other labels should be ignored. 

In practice, there is no change in labels being used (see also [#119](https://github.com/w3c/w3c.github.io/pull/119) ).

**Comment by annevk** [comment]
Thanks @plehegar, changes made. #313 adjusts our script.
