### ISSUE TITLE
Add robots.txt to forbid indexing commit-snapshots

### ISSUE THREAD

**Issue by annevk** [whatwg/meta#32]
Doesn't make much sense to have them indexed.

**Comment by domenic** [comment]
Strongly agreed. I guess as part of deploy.sh?

**Comment by annevk** [comment]
Yeah, that's probably the easiest. I don't think we have any custom robots.txt.

**Comment by annevk** [comment]
> ssh whatwg
    > find . -name "robots.txt"
    ./htmlbuild/html/robots.txt
    ./whatwg.org/robots.txt

Not sure why htmlbuild has one. The other wouldn't be affected here.

**Comment by phonedude** [comment]
better suggestion: add rel="canonical" on the snap shots so search engines know what URI they *should* index instead.  I've added it as a separate issue: https://github.com/whatwg/meta/issues/33
