### ISSUE TITLE
Does a CSS counterpart to the `whatwg/html` repository exist?

### ISSUE THREAD

**Issue by RokeJulianLockhart** [whatwg/meta#328]
Posted here per https://whatwg.org/#:~:text=Queries%20can%20be%20directed%20either%20as%20a%20new%20meta%20issue:

> Queries can be directed either as a [new meta issue](https://github.com/whatwg/meta/issues/new)

**Comment by annevk** [comment]
That would be https://github.com/w3c/csswg-drafts. Surprisingly not mentioned on https://www.w3.org/Style/CSS/.
