### ISSUE TITLE
Sunsetting forums.whatwg.org

### ISSUE THREAD

**Issue by domenic** [whatwg/meta#34]
- forums.whatwg.org: redirect to https://github.com/whatwg/, or maybe the IRC wiki page?
- svn.whatwg.org: redirect to https://github.com/whatwg/, and stop running a SVN server there?
- help.whatwg.org: redirect to https://html.spec.whatwg.org/dev/ ?

Harder:

- images.whatwg.org: I am sure people link to this, but it seems also quite old. I wonder who still links to it and whether we can come up with redirects for it without breaking lots of things.

**Comment by annevk** [comment]
images is used by https://whatwg.org/specs/web-apps/ and similar directories I suspect. While we could put up redirects and host the remaining on resources.whatwg.org, it might be just as easy to leave it up since either we just host a bunch of files there or we host a redirect file.

We could redirect forums to whatwg/meta maybe?

cc @zcorpan

**Comment by zcorpan** [comment]
No strong opinion on where to redirect... But suggest https://whatwg.org/ as another option to consider. (If it's not as something else, maybe we can improve that page?)

**Comment by foolip** [comment]
svn.whatwg.org and help.whatwg.org are now redirecting.

images.whatwg.org is still up and has some overlap with https://whatwg.org/images/. Should we consolidate and redirect?

forums.whatwg.org is a problem, it'd be nice to keep a static copy of it around, but work to create and validate.

https://github.com/whatwg/misc-server/issues/7 is related.

**Comment by zcorpan** [comment]
https://automatthias.wordpress.com/2016/05/05/phpbb-static-archive/ suggests using https://github.com/automatthias/phpbb3-static

**Comment by annevk** [comment]
@foolip I don't think it's worth the hassle to try to get rid of images.whatwg.org since we'll have to keep it running anyway. We could run that deduplicate script you mentioned the other day and used on encoding.spec.whatwg.org to reduce size.

**Comment by annevk** [comment]
All that remains here is forums.whatwg.org. Adjusted title accordingly.

**Comment by annevk** [comment]
https://github.com/whatwg/misc-server/commit/119b3fb494bfc8f97e210b27c08c6eb61c43ffc5
