### ISSUE TITLE
People have issues unsubscribing from whatwg mailing lists

### ISSUE THREAD

**Issue by zcorpan** [whatwg/meta#36]
http://lists.whatwg.org/listinfo.cgi/whatwg-whatwg.org does not work for people because of HSTS.

Possible fixes:

* DreamHost adds Let's Encrypt to their mailing list service
* We move the mailing list to our own server
* We configure the mailing list to not suggest that URL anywhere. This was changed for the footer when we switched to https but the broken URL still exists in the `List-Subscribe` header as well as in Digest emails.

**Comment by annevk** [comment]
This depends on https://github.com/whatwg/misc-server/issues/7#issuecomment-350661327, basically.

**Comment by foolip** [comment]
Tracking that in https://github.com/whatwg/misc-server/issues/75 now.

**Comment by annevk** [comment]
We don't need to track this independently from migrating/dismantling lists.whatwg.org somehow.
