### ISSUE TITLE
Centralized commit title/message rules

### ISSUE THREAD

**Issue by annevk** [whatwg/meta#37]
Over in whatwg/dom a PR by @snuggs made me realize we should really have central commit title/message rules.

They should probably consist of the first three paragraphs of https://github.com/whatwg/meta/blob/master/TEAM.md#handling-pull-requests.

Should we just host those in a Markdown file in this repository and link to it from all over? Perhaps updating https://github.com/whatwg/meta/blob/master/CONTRIBUTING.md would be best?

**Comment by domenic** [comment]
It might be good to have a separate file, where we could also pull in relevant portions of https://github.com/erlang/otp/wiki/Writing-good-commit-messages (with modifications such as no strict 50 character limit on the initial line).

**Comment by snuggs** [comment]
FWIW @domenic I don't know if that's a setting here but when I did my PR it started throwing red messages @ 50CHARS. Perhaps you are speaking of conventional enforcement and just so happens to be a github feature.

**Comment by snuggs** [comment]
NVM. Just now saw `erlang`.

**Comment by snuggs** [comment]
@annevk where shall we open a PR for this? Would like to take a crack at it if that helps. Seems to be overlapping enough to perhaps be `whatwg/meta`? You would know better than me.

**Comment by annevk** [comment]
Yeah, this repository would be a good place. Thanks for taking this on! Maybe something like "COMMITS.md".

**Comment by annevk** [comment]
Although a new heading under pull requests in https://github.com/whatwg/meta/blob/master/CONTRIBUTING.md also doesn't seem too bad. Not sure if @domenic fully considered that option.

**Comment by domenic** [comment]
I think it's dense enough that I'd prefer a new document linked from Contributing.md.

**Comment by snuggs** [comment]
Great feedback! Didn't know where to start. Will start drawing up a stick figure tomorrow. Am currently enjoying a Saturday (for once this year).

**Comment by snuggs** [comment]
@annevk @domenic thanks for your patience. I've had some personal family issues to address and had to come to the other side of the country in SF. That being said... Happy Friday 🎉  

Please advise 👀  https://github.com/whatwg/meta/pull/40

**Comment by snuggs** [comment]
@annevk unless there are other nits should be good on this one. https://github.com/whatwg/meta/pull/40

**Comment by snuggs** [comment]
About our character limit of 72. We may need to add a light edge case for referencing comments & shas. Often the URL alone is longer than 72 characters. The upside is Github truncates.

For example: https://github.com/whatwg/meta/pull/40/commits/d47e8b5330287c3e7193c8ab6b871b88af2d6485

![capture d ecran 2017-11-07 a 18 05 32](https://user-images.githubusercontent.com/38223/32507013-8a45f7ae-c3e6-11e7-8a1e-da385f3b5499.png)

**Comment by domenic** [comment]
@snuggs good point. I think we can mention that we can have exceptions for single "words" that are longer than 72 characters, like a URL.

**Comment by snuggs** [comment]
@domenic addressed in https://github.com/whatwg/meta/pull/46
