### ISSUE TITLE
good first bug

### ISSUE THREAD

**Issue by annevk** [whatwg/meta#43]
GitHub apparently helps new folks find the "good first issue" label. Should we attempt to switch from "good first bug"? That might have some repercussions for existing links, but given native support, maybe it's worth it?

We should also document whatever we end up doing in LABELS.md.

cc @sideshowbarker @zcorpan @foolip @domenic

**Comment by foolip** [comment]
What does the native support look like, what will people see?

**Comment by annevk** [comment]
<img width="490" alt="screen shot 2017-10-12 at 12 20 16" src="https://user-images.githubusercontent.com/1544111/31491474-bb4509f2-af47-11e7-91c9-9cc5a870e9a7.png">
Is all I have unfortunately.

**Comment by annevk** [comment]
https://help.github.com/articles/helping-new-contributors-find-your-project-with-labels/ doesn't really say much either. Maybe it's not a big deal for now.

**Comment by domenic** [comment]
I was for switching, but if we indeed don't see any benefits yet, let's wait until we see what "native support" means.

**Comment by izulien** [comment]
As a complete outsider, I did find the project in general due to the Good First Issue wording.  Ideally though this would help users with low PR/contributions to find projects actively looking for help (label:"help wanted") or looking to help new users(label:"good first issue").

A decent portion of the "Good First Issue" items that I've seen currently aren't very great intro items.  I would suggest use that label for typo corrections and other super minor items.  Essentially leaving the label for users to try out PR in general.  These types of issues also don't really need to be handled by your more experienced programmers.

**Comment by domenic** [comment]
> As a complete outsider, I did find the project in general due to the Good First Issue wording.

Can you explain what source linked you to the good first issues? Especially since we don't have any tagged as such?

**Comment by izulien** [comment]
Github.com directly mentions it if you have little to no PRs outside of your own / managed repositories.

I of course didn't read all the way so I didn't do the recommended search "label:"good first issue"".  If the search tag label: is missing it will simply search all items.

**Comment by sideshowbarker** [comment]
It seems some GitHub docs do now mention the specific labels *good first issue* and *help wanted*:

* https://help.github.com/articles/finding-open-source-projects-on-github/#searching-using-labels
   > You can search for labels on issues and pull requests to find projects that are actively seeking contributors. For example, if you are a first time contributor, search for issues with the `good first issue` label to find projects to start on. You can also search issues and pull requests with the `help wanted` label to find projects that are actively seeking contributions

* https://help.github.com/articles/about-labels/#using-default-labels
  > GitHub provides default labels in every new repository. You can use these default labels to help create a standard workflow in a repository:
  >
  > Label | Description
  > -- | --
  > ... | ...
  > `good first issue` | Indicates a good issue for first-time contributors
  > `help wanted` | Indicates that a maintainer wants help on an issue or pull request
  > ... | ...


So the above also seems to indicate that all new repos now get created with `good first issue` and `help wanted` among the default set of labels.

**Comment by domenic** [comment]
> Github.com directly mentions it if you have little to no PRs outside of your own / managed repositories.

Fascinating, would you happen to have a screenshot or similar? It'd be quite helpful to see it in action.

**Comment by annevk** [comment]
See "X issues need help":
<img width="540" alt="screen shot 2017-11-25 at 7 33 07 am" src="https://user-images.githubusercontent.com/1544111/33228061-f512bc14-d1b2-11e7-8a04-152749f8d1f7.png">
<img width="568" alt="screen shot 2017-11-25 at 7 35 11 am" src="https://user-images.githubusercontent.com/1544111/33228085-3bbd8432-d1b3-11e7-9235-9a67f9dfe7a4.png">
Seems to work for "help wanted" or "good first issue", but `/whatwg` doesn't have them since we use "good first bug".

**Comment by annevk** [comment]
FYI: given the above I plan to make this change as soon as next week or whenever I get around to it. Please raise concerns soon.

**Comment by annevk** [comment]
(I ran `grep -r "good first bug" *` across all GitHub repositories I have locally and created PRs for those matched.)

**Comment by domenic** [comment]
We also need to update at least one blog post.

**Comment by annevk** [comment]
Updated https://blog.whatwg.org/github and https://blog.whatwg.org/html-standard-now-more-community-driven.
