### ISSUE TITLE
Protecting master branches everywhere in order to give more folks write access

### ISSUE THREAD

**Issue by annevk** [whatwg/meta#45]
Giving more folks write access will empower them to add labels, assign issues, and create and update branches. That seems like a good thing as we're all here to make the web better and any mistakes are easily corrected.

We don't necessarily want everyone to have access to the couple administrative repositories however so a way to manage this would be to have a large contributor team that has write access to each repository. We'd then add most folks to this team.

Before we do that we need to ensure that the master branches are protected, as mistakes are more costly for those and other than through pull requests nobody should be meddling with those anyway.

**Comment by domenic** [comment]
I'd prefer this to be a per-editor/per-spec decision. I'm not really comfortable expanding the permission to close, assign, or label issues beyond the set of editors for Streams.

**Comment by annevk** [comment]
Another risk here is that local branches can be used to extract keys from Travis. Until that is solved this is probably not a good idea.

**Comment by annevk** [comment]
I've become more hesitant about this idea as branches are somewhat important too, especially long-lived ones. Having a separate permission for labels is really what we want. Closing this until that becomes a thing.

**Comment by annevk** [comment]
(GitHub also makes it a lot easier with GitHub Desktop to deal with and manipulate remote PR branches.)
