### ISSUE TITLE
Meta: Request to join Components team

### ISSUE THREAD

**Issue by snuggs** [whatwg/meta#47]
We currently have the following teams established:

- a11y
- canvas
- **components**
- html-parser
- i18n
- loader
- media
- modules

Am curious where a briefing of each team
(particularly components, a11y, media, and modules) would reside.
To be clear only curious about the last three.
I'm explicitly requesting  (and assuming web) components,
only because i've been following the spec maturity for a few years now.
Even still i'm not 100% certain this is the "components" i'm assuming.

If so...This would be an honor and a privilege 🙏 
how can I be down? :-)

Lastly when does a group get "christened" and which ones are on the horizon. Sheer curiosity.

Thanks in Advance!

**Comment by annevk** [comment]
We don't have descriptions of these teams. a11y is for accessibility-related matters; canvas the canvas element and its APIs; components is for custom elements, shadow trees, and related technologies; html-parser for the HTML parser; i18n for internationalization-related matters; loader for the Loader idea; media for the HTML media elements and their API; modules for JavaScript modules.

Teams are created whenever as needed. Typically when we find ourselves pinging them same group of people for similar reasons. Which reminds me that I added security (for security-related matters) and have not documented that here.

**Comment by annevk** [comment]
(I invited you to the team by the way. I think I had already invited you to the WHATWG organization, but it seems you have not yet joined.)

**Comment by snuggs** [comment]
OH WOW!!!! Man my github messages are CRAZY! You'll have to school me on how you stay sane.
💻 🏃

**Comment by annevk** [comment]
Only watch what you can actually reasonably watch. Aggressively unsubscribe from all issues that don't concern you. Use /notifications, no email, to avoid many notifications for a single thread.

**Comment by snuggs** [comment]
This is an honor @annevk 🙏
