### ISSUE TITLE
Using SSH securely

### ISSUE THREAD

**Issue by annevk** [whatwg/meta#5]
Currently we ignore validation of the server we are copying resources into. I don't see an immediate attack, but we should set the correct example. It will also help us if it starts mattering at some point.

PRs created thus far:

* https://github.com/whatwg/url/pull/202
* https://github.com/whatwg/dom/pull/397

One thing that would be nice if we could deduplicate this known_hosts resource somehow. Or maybe add the information into `.travis.yml`. Getting quite a few boilerplate resources making the repositories look harder to work with than they are.

**Comment by domenic** [comment]
I guess we could host a single known_hosts file (with all the servers and hostnames) in whatwg/meta and curl it down as part of the deploy script.

**Comment by annevk** [comment]
I like your plan in #6. Since we only connect to a single server known_hosts probably only needs to contain a single entry. Although the username does need to vary.

I'm happy to not land these PRs if we fix it more generally.

**Comment by annevk** [comment]
I think it could actually be as easy as having the deploy script write out a known_hosts resource with just the IP address and the public key and then make use of that.

**Comment by annevk** [comment]
This is #6 now.
