### ISSUE TITLE
Branch snapshots

### ISSUE THREAD

**Issue by annevk** [whatwg/meta#52]
Most standards (HTML Standard excluded) have a `branch-snapshots/` directory. This hosts a copy of the standard reflecting the last commit in a PR. If the branch name used in the PR gets reused, the copy gets overridden. If the branch name is not local, it doesn't get created.

PR Preview has similar functionality, though I believe no overriding takes place and non-local branch names do not matter.

It would be nice if we could reconcile the two. I don't think we need to keep distinct solutions.

cc @tobie @domenic @foolip

**Comment by foolip** [comment]
Not having the branch-shapshots/ directories at all and just using PR Preview would be fine with me.

**Comment by foolip** [comment]
Should we delete existing branch snapshots, or just stop deploying them?

**Comment by annevk** [comment]
We should probably keep them, given that PR Preview used to link to them directly (at least for some specs).

**Comment by foolip** [comment]
Branch snapshot deploy is gone, but existing ones will be left alone.
