### ISSUE TITLE
PR Preview hosting

### ISSUE THREAD

**Issue by annevk** [whatwg/meta#53]
We need to sort out how to host PR Preview resources. Currently they use Amazon S3. We could continue to use that or create some kind of space where the PR Preview tool can upload resources to (just HTML or also other resources found in the repository?).

Since these resources can come from untrusted sources we should consider not hosting them on whatwg.org. Perhaps "preview.whatwg.org" is sufficient though I'm a little wary of that still due to cookies.

cc @tobie @domenic @foolip

**Comment by domenic** [comment]
Is there any downside to continuing to use S3?

**Comment by tobie** [comment]
> Is there any downside to continuing to use S3?

None. It already works. It's dirt cheap (we'd need a 100x the traffic of the whole of pr-preview to start having to pay $5/month). It can easily be associated with a subdomain or custom domain (if you're concerned about security issues).

The only downside I can see is that it's complicated to move files from one S3 bucket to another (or to pass buckets around). 

In order to mitigate that, we should just create a dedicated WHAT WG S3 bucket, either on a WHAT WG AWS account, if you already have one setup, or on a new account I'll create (which we'll move to use one of your email addresses once I've done setting it up).

**Comment by annevk** [comment]
It's WHATWG (no space). Using S3 sounds fine.

**Comment by tobie** [comment]
> It's WHATWG (no space).

Fixed.

**Comment by annevk** [comment]
WHATWG doesn't have an AWS account by the way. Sounds like the way forward here is that you create one. We have a joint administrative email address I can relay in private when the time comes.

**Comment by tobie** [comment]
Do you have a credit card you use for this stuff too?

**Comment by foolip** [comment]
No WHATWG-branded credit cards yet, but someone could expense it :)

**Comment by tobie** [comment]
> No WHATWG-branded credit cards yet

What are you all doing, really?

>  but someone could expense it :)

There shouldn't be any expenses. AWS just wants a credit card on file.

**Comment by foolip** [comment]
Sounds like the person whose credit card is used should be the one to set this up. Is there such a thing as a team account, or should it be an account tied to someone's email?

**Comment by tobie** [comment]
So I created a new account for now which we can tweak once we know who's credit card, billing address, etc. to use down the road.

**Comment by foolip** [comment]
I suggest @domenic because more VAT is added in Europe.

**Comment by foolip** [comment]
(In case there will be expenses down the road.)

**Comment by tobie** [comment]
So it seems we have to name S3 buckets after the domain or subdomain name we want to use. Chaing S3 bucket names being complicated, it would be nice if we could:

1. decide on whether to use a domain or subdomain for this,
2. decide on its name.

**Comment by snuggs** [comment]
@foolip FWIW let me know where I can help. I not only work with Digital Ocean but also Engine yard (https://engineyard.com) who basically handle all this stuff for us. Also get instances **always** cheaper than whatever plan we can get on. They are just a dev ops wrapper around AWS. Will also eliminate any credit card red tape as well. We can have a turn around of less than 24hrs. Just say the word. No harm no foul if not needed.

**Comment by annevk** [comment]
We cannot use a subdomain as the content is not always trusted and I'd like a maximally safe setup, if only to set the right example.

We can use a domain. I like whatpr.org. If we want it to contain whatwg in full, I'd suggest whatwg-sandbox.org (if we foresee more needs for a "dumping" ground) or whatwg-preview.org. I originally liked whatwg.io, but I don't think it's worth USD 50 a year.

We can also continue to not have a domain in which case I would suggest naming the bucket WHATWG Preview.

The main reason I think we should use a domain is that there's some benefit if these URLs get shared. The receiver can then infer it's related to a WHATWG Standard PR and not just a random standards-related document on S3. And if the URL goes dead for some reason it's also clear where to go to find out what happened to it and what it might have represented.

**Comment by foolip** [comment]
whatpr.org is cute, LGTM.

**Comment by annevk** [comment]
I registered whatpr.org. @tobie let me know where to point the nameservers and it's all yours.

**Comment by tobie** [comment]
ns-368.awsdns-46.com.
ns-810.awsdns-37.net.
ns-1345.awsdns-40.org.
ns-1938.awsdns-50.co.uk.

**Comment by annevk** [comment]
Done, it seems the trailing dot is not accepted by TransIP. Probably not worth complaining about.

**Comment by tobie** [comment]
All of this lower level stuff could do with some UX love across the board.

**Comment by tobie** [comment]
And… apologies! I made a mistake, had to start from scratch and got assigned a different set of DNS servers:

ns-1502.awsdns-59.org.
ns-128.awsdns-16.com.
ns-2004.awsdns-58.co.uk.
ns-959.awsdns-55.net.

Would appreciate if you could change those.

**Comment by annevk** [comment]
Done (again without trailing dots).

**Comment by domenic** [comment]
This seems to be all working, right? Shall we close?

**Comment by tobie** [comment]
\o/

**Comment by annevk** [comment]
Yeah, we'll leave removing branch snapshots to #52.

**Comment by annevk** [comment]
Thanks @tobie!

**Comment by tobie** [comment]
Thanks Mozilla!

**Comment by foolip** [comment]
I just took a look at a recent PR, that's very, very nice! Thanks universe!
