### ISSUE TITLE
SSL failure on html.spec.whatwg.org: wrong site/certificate

### ISSUE THREAD

**Issue by hiroshige-g** [whatwg/meta#54]
Currently https://html.spec.whatwg.org/ has a certificate of sni.dreamhost.com, and thus is blocked by Web browsers.
Looks like html.spec.whatwg.org is resolved to a dreamhost IP address by DNS, while others (at least spec.whatwg.org, fetch.spec.whatwg.org, and dom.spec.whatwg.org) are resolved to a DigitalOcean IP address.

**Comment by hiroshige-g** [comment]
And wgetting the page results in "Site Not Found" page by dreamhost.

**Comment by sideshowbarker** [comment]
I think the problem must be that `html.spec.whatwg.org` is resolving to `75.119.197.251` for you.

If it resolves instead to `165.227.248.76` then you won’t get an cert error.

The DNS was recently switched from `75.119.197.251` to `165.227.248.76`, so you must be hitting a DNS resolver that’s still got the old IP address cached. (Assuming you don’t have it hardcoded in an `/etc/hosts` or whatever to resolve to `75.119.197.251`…)

**Comment by annevk** [comment]
Apologies for the outage. I'm closing this given that this was somewhat expected due to the DNS switch. Please let us know if the problem persists. Hopefully we'll have a service worker in place next time we need to do something like this.

**Comment by foolip** [comment]
Does anyone know how to avoid this kind of thing? Is it to keep the old server running for a week or so after the DNS update? I don't think that easily doable with DreamHost, but something to keep in mind next time.
