### ISSUE TITLE
Consolidate human- and machine-readable Living Standard/Workstream lists

### ISSUE THREAD

**Issue by domenic** [whatwg/meta#57]
An ideal setup would be a single machine-readable (JSON) document listing:

- Workstreams
  - Name
  - Scope
  - Short, "database" name (used by participate.whatwg.org code)
  - Editor
    - Name
    - Email address
  - Living standards. Per living standard:
    - Authors (usually a superset of workstream editor; used for bibliographies and attribution, not decision-making power)
    - Short all-caps name for cross-references
    - Full citable title that includes "Standard" at the end
    - Description (currently seen on spec.whatwg.org)
- Non-workstream things people might cite
  - See BOOKS, DOMPARSING, FIGURES, JAVASCRIPT, LOADER in https://resources.whatwg.org/biblio.json

Right now this data is scattered across:

- [spec.whatwg.org as HTML](https://github.com/whatwg/whatwg.org/tree/master/spec.whatwg.org/index.html)
- [idea.whatwg.org as HTML](https://github.com/whatwg/whatwg.org/blob/master/idea.whatwg.org/index.html)
- [whatwg/sg's Workstreams.md](https://github.com/whatwg/sg/blob/master/Workstreams.md)
- [participate.whatwg.org config.json](https://github.com/whatwg/participate.whatwg.org/blob/master/config.json)
- https://resources.whatwg.org/biblio.json

The new resource would live in whatwg/sg since the SG controls scope changes/the creation of new workstreams/etc.

From this new machine-readable data source, we would then

- Generate spec.whatwg.org
- Generate idea.whatwg.org
- Generate whatwg.org/workstreams
- Generate https://resources.whatwg.org/biblio.json
- Update participate.whatwg.org code to consult this canonical resource
- Update labels.py to consult this canonical resource

**Comment by guest271314** [comment]
What needs to be done? Where is help needed to realize the goal of this issue?

**Comment by annevk** [comment]
@domenic one problem with putting this in whatwg/sg is that changes to whatwg/sg can take a long time.

(Having this would also help with further automating our label setup.)

**Comment by annevk** [comment]
"whatwg/sg's Workstreams.md" and "participate.whatwg.org config.json" disagree on how Workstreams are named. Per discussion with @domenic the latter is likely wrong so those names will subtly change.

**Comment by domenic** [comment]
(The effect of this would be changes visible on https://participate.whatwg.org/agreement.)

**Comment by annevk** [comment]
https://github.com/whatwg/sg/pull/111 and https://github.com/whatwg/whatwg.org/pull/303 are my attempt at solving this. (I also added idea.whatwg.org as target.)

**Comment by domenic** [comment]
Amazing stuff; looking forward to reviewing!

You haven't done participate.whatwg.org's config.json yet, right? I'd be happy to take that on myself; in particular figuring out a way that uses Node.js tools and works for both local development and deploy.

**Comment by annevk** [comment]
Yeah, that's the one that's remaining. Thanks for taking that!

**Comment by annevk** [comment]
@domenic so for labels.py I need all repositories that host a standard. I think it's safe to assume that standards and repos are 1:1 and that the shortname of a standard in its URL is 1:1 with the repo name. Do you agree or do we need a specific shortname or reponame or both field in addition to the URL?

**Comment by tobie** [comment]
Let me know when we need to update specref.

**Comment by annevk** [comment]
@tobie I've made it so that no changes are required for you. I'll update OP. (My rationale is that biblio.json has a semi-standardized format and Steering Group's db.json does not and I'm not sure to what extent we want to commit to its stability, especially initially.)

**Comment by domenic** [comment]
> I think it's safe to assume that standards and repos are 1:1 and that the shortname of a standard in its URL is 1:1 with the repo name. Do you agree or do we need a specific shortname or reponame or both field in addition to the URL?

I agree with that. I believe we make that assumption in some of the Bikeshed boilerplate too.

**Comment by annevk** [comment]
The whatwg/sg repository now contains db.json. What remains here are

* Update participate.whatwg.org code to consult this canonical resource
* Update labels.py to consult this canonical resource

as far as I can tell. https://github.com/whatwg/spec-factory also needs a small tweak to no longer fetch the file from a branch.

**Comment by annevk** [comment]
This is all done now, hurray!
