### ISSUE TITLE
Blog: "Sunsetting the JavaScript Standard" URL dead (https://blog.whatwg.org/javascript) 

### ISSUE THREAD

**Issue by SamB** [whatwg/meta#59]
[I didn't see any more specific way to report technical issues with the blog, so I'm reporting this here.]

It's still there; it shows up just fine on <https://blog.whatwg.org/2016/08>.  It's even still said to have the URL <https://blog.whatwg.org/javascript> that's linked to from e.g. <https://github.com/whatwg/javascript>.  There's just *one* problem: that URL no longer actually **works** :-(.

According to Google, this is actually a very new problem: they still have the page cached as it appeared on Dec 4, 2017 19:29:36 GMT.

**Comment by annevk** [comment]
Thanks, I suspect a WordPress update added some kind of folder there. That sucks.

**Comment by annevk** [comment]
I'm not sure what our options are here, perhaps we can fiddle a bit with the `.htaccess` rules, but that might not be a long term solution either.

cc @foolip

**Comment by foolip** [comment]
Well that's annoying! I'm not sure exactly how to fix it in a way that doesn't break on each upgrade, except perhaps to rename the post and redirect just /javascript, but not /javascript/foo.

@annevk, did you upgrade the blog today, or is this from last week?

**Comment by annevk** [comment]
This is from last week most likely, no updates this week.

**Comment by foolip** [comment]
I found https://stackoverflow.com/questions/21706067/apache-doesnt-serve-files-in-javascript-directory-why.

It's actually not because of WordPress, but because /etc/apache2/conf-enabled/javascript-common.conf has:
```
Alias /javascript /usr/share/javascript/

<Directory "/usr/share/javascript/">
	Options FollowSymLinks MultiViews
</Directory>
```

**Comment by foolip** [comment]
This is now fixed, but unfortunately the setup for this server isn't in version control. https://github.com/whatwg/misc-server/pull/58 is a test that'll at least make sure it doesn't regress.
