### ISSUE TITLE
Update various standards to link to whatwg/meta documents

### ISSUE THREAD

**Issue by annevk** [whatwg/meta#65]
It seems we updated HTML, but, e.g., https://github.com/whatwg/dom and https://github.com/whatwg/streams still refer to the Erlang wiki and generally don't seem to point to the guidelines here.

Fixing #64 first would be good though.

**Comment by domenic** [comment]
whatwg/url links to whatwg/html's TEAM.md; probably it should link here.

**Comment by snuggs** [comment]
Shouldn't we be linking to https://github.com/whatwg/meta/blob/master/TEAM.md?

**Comment by annevk** [comment]
Yes (well, MAINTAINERS.md), everything should link here (unless they need a more specific MAINTAINERS.md that depends on this one).

**Comment by annevk** [comment]
Should we also add CONTRIBUTING.md to each standard that simply defers to the one here? That way you get to see it when creating a PR.

**Comment by snuggs** [comment]
I think we should @annevk.

**Comment by snuggs** [comment]
@annevk "*Helps with* whatwg/meta#65." << noted

**Comment by annevk** [comment]
I've now created PRs (see above) for everything that referenced a TEAM.md resource.

But there might be more to be done here as not all other README's and such are likely accurate and not everything references CONTRIBUTING.md yet.

**Comment by snuggs** [comment]
Thanks a ton @annevk lookin good!

**Comment by annevk** [comment]
I updated all open PRs I created per feedback from @snuggs. Review on them appreciated.

**Comment by annevk** [comment]
What is remaining here is https://github.com/whatwg/streams/pull/867 and https://github.com/whatwg/console/issues/125. Seems this issue has served its purpose. There's something to be said for getting even more consistency, but we'll just keep trying whenever we need to make changes to many repositories.

**Comment by annevk** [comment]
Thanks for the help @snuggs!

**Comment by snuggs** [comment]
@annevk Just doin' my "job". Little by little Getting better by the day. :-)

I still don't see how you and @domenic are able to maintain this all conceptually over the years. Although I'm picking up on little tricks on how to organize tasks. And what to aggressively NOT pay attention to. But I digress.

I'll see you on the other issues.

**Comment by leonardoadame** [comment]
Please see the [WHATWG Contributor Guidelines](https://github.com/whatwg/meta/blob/main/CONTRIBUTING.md).
