### ISSUE TITLE
HTML issue

### ISSUE THREAD

**Issue by sudokus999** [whatwg/meta#67]
I want horizontal and vertical splitters in HTML. Also be able to make a side of an element a splitter similar to how borders are changed, means each element might have 4 predefined splitters. When I change its size other elements, if possible, around it fill the freed space. This is how I want it to be. 

I want a vertical line in HTML !

**Comment by annevk** [comment]
I'm not entirely sure what you mean, but it sounds like you're looking for CSS extensions, perhaps?

**Comment by domfarolino** [comment]
I think this can be closed
