### ISSUE TITLE
Standardize more organization-wide labels

### ISSUE THREAD

**Issue by annevk** [whatwg/meta#80]
Sometimes even across organizations:

* addition/proposal
* removal/deprecation
* do not merge yet
* needs implementer interest
* topic: shadow
* topic: custom elements
* waiting for tests (rename to "needs tests"?)
* interop
* needs compat analysis
* normative change

**Comment by domenic** [comment]
- compat

**Comment by annevk** [comment]
I created #81 with both your feedback taken into account. (I already adjusted whatwg/html to use "needs tests".)

**Comment by foolip** [comment]
Came across this when pondering what scripts to add for https://github.com/whatwg/meta/issues/152. Is anyone running labels.py regularly?

**Comment by annevk** [comment]
I run it when we do updates.
