### ISSUE TITLE
Joining the SG

### ISSUE THREAD

**Issue by edent** [whatwg/meta#87]
I am interested in understanding how my organisation can join the Steering Group.

The development of the web belongs to more than just four browser vendors.  I think it would be helpful if the SG were comprised of a more diverse viewpoint.

**Comment by cwilso** [comment]
The WHATWG community is, and always has been, more than just four browser vendors, and it is in that community that the development of the web happens. 

That said, it would be useful to have a direct pointer from the SG on "don't think the SG is diverse enough?  Here's where to file an issue/volunteer as SG member/whatever."

**Comment by edent** [comment]
From  https://whatwg.org/sg-agreement#steering-group-member

> The purpose of the Steering Group is to govern and guide the WHATWG, an open, efficient forum for development of Living Standards (useful technical specifications, with intellectual property commitments from contributors) plus associated documentation, code, and other materials and activities that relate to or support web technologies, as determined by the Steering Group.

I'm interested in helping with the governance and guidance of WHATWG.  What is the process for joining the SG so we can participate in this?

**Comment by annevk** [comment]
The SG is basically the end of WHATWG's escalation path (compare it to the Director role at the W3C) and there's no process to join it.

You should feel free to contribute to Workstreams and policy documents however. There's no need to be a member of the SG for any of that.

**Comment by edent** [comment]
You say there's no process to join it.  As per https://whatwg.org/sg-agreement#a-decisions-requiring-unanimous-consent

> By unanimous consent, the Steering Group may: Add a Steering Group Member.

We'd be interested in being part of the escalation path.  

You also say that "there's no need to be a member of the SG for any of that."

> By Consensus, the Steering Group may take any other action regarding the WHATWG, including but not limited to creating, implementing, and modifying policies and agreements of the WHATWG and of the Steering Group. 
> https://whatwg.org/sg-agreement#b-other-decisions-by-consensus

How can we become part of that consensus making body?

I'd like to be part of the governance structure to ensure that everybody's voice is heard.

**Comment by annevk** [comment]
It's probably best if you ask the SG directly at https://github.com/whatwg/sg/issues and close this issue. I don't think we can help you here.
