### ISSUE TITLE
Stop commit snapshots for PRs

### ISSUE THREAD

**Issue by annevk** [whatwg/meta#9]
I wonder if it's really useful to have commit snapshots for PRs. It seems that latest branch snapshot would be sufficient.

There's two concerns:

* Making /commit-snapshots/ reflect master would make it easier to go through. It would reflect linear history just like our Git usage.
* Amount of space used on the server.

**Comment by zcorpan** [comment]
> It seems that latest branch snapshot would be sufficient.

Agree.

**Comment by domenic** [comment]
This should be a relatively easy change. Probably best to do as part of #6.

> > Amount of space used on the server.

I was told by @Hixie that we have unlimited space :). Maybe not true after #8 of course.

**Comment by Hixie** [comment]
On Dreamhost we have unlimited space, yes.
