### ISSUE TITLE
i18n labels for the whatwg/html issue list

### ISSUE THREAD

**Issue by r12a** [whatwg/meta#90]
The whatwg/html repo currently has labels for i18n-comment and i18n-tracking. Recently, however, i have begun labelling relevant issues in the W3C spec repos with whatever's relevant from the following list of labels. The effect is that if there's an issue related to Arabic or Hebrew, such as a bidi topic, experts in the Arabic/Hebrew groups are notified of activity related to that issue. 

- i18n-jlreq
- i18n-ilreq
- i18n-elreq
- i18n-clreq
- i18n-hlreq
- i18n-alreq
- i18n-sealreq
- i18n-mlreq
- i18n-tlreq
- i18n-klreq 

Would it be ok to add those labels? (If it helps, we typically use the same colour as the other two i18n- labels.)

Also, would it be possible to give me access rights so that i can create but more importantly set the labels myself (which may make things faster and easier for others)?

**Comment by annevk** [comment]
I gave you write access to whatwg/html which should give the ability to add these labels.

Eventually they should probably be documented in https://github.com/whatwg/meta/blob/master/LABELS.md and automated as proposed in #81.

**Comment by r12a** [comment]
Thanks.  I added just a few for now - ones i think will be useful in the near term. I'll add others later as and when the need arises.  I only labelled one issue for now, but I'll scan the open issues again when i get a moment and label other issues as needed. 

I also documented their use in descriptions and in LABELS.md.

**Comment by r12a** [comment]
Pull request for LABELS.md at https://github.com/whatwg/meta/pull/91

**Comment by annevk** [comment]
@r12a do you still want to add those missing? You can now modify `labels.json` and run `./labels.py --update` to add the missing labels. I can then run the `./labels.py` script with a correct token and get these labels added to all repositories, along with their descriptions.

**Comment by r12a** [comment]
@annevk  the following are the groups that are currently label candidates: elreq, mlreq, sealreq, tlreq.  It's not clear to me, however, that there will be much in HTML that would need those labels (at least at the moment), and two of those groups are not yet fully functional, so i though maybe it would be better to hold back, purely in order to keep the length of the label list short, until such time as the need arises.  However, if you think there's no harm, i could add them now.

**Comment by annevk** [comment]
Happy to wait until they're fully functional.

**Comment by annevk** [comment]
I'm going to close this. If you want to add more organization-wide labels, please feel free to update this repository as per the above instructions.

**Comment by r12a** [comment]
Got it. Thanks.
