### ISSUE TITLE
Tooling to update "meta" resources across repositories

### ISSUE THREAD

**Issue by annevk** [whatwg/meta#95]
Having done a few rounds, I'm starting to think it would be good if we had tooling to update `README.md`, `.gitignore`, `Makefile`, etc. resources across repositories in a simplified manner. That would also keep them more consistent.

**Comment by woojgffkiscklhddxsb** [comment]
#95

**Comment by foolip** [comment]
https://github.com/w3c/validate-repos serves a similar purpose for W3C repositories, although it's currently only detecting discrepancies and doesn't provide tooling for fixing them. That possibility was raised in https://github.com/w3c/validate-repos/issues/74 however.

**Comment by annevk** [comment]
https://github.com/annevk/spec-factory allows for this now. https://github.com/annevk/spec-factory/issues/1 lists some breakage, but it's already good enough to use I think.

I'm wondering if there are other files folks want to see tackled before I open the first wave of PRs to align things a bit. I might play a bit with README.md if I get the chance, but that's probably the trickiest as we don't have agreement on formatting. (It could still help identifying differences in other sections though.)

**Comment by annevk** [comment]
https://github.com/whatwg/spec-factory/issues has a number of follow-up issues if anyone is interested in helping out. Having updated a number of specifications with it already I think we can consider this issue to be closed.
