### ISSUE TITLE
Migrate Travis CI to GitHub Apps

### ISSUE THREAD

**Issue by annevk** [whatwg/meta#96]
I noticed GitHub services is being deprecated and no longer supported in October. I plan to follow https://docs.travis-ci.com/user/legacy-services-to-github-apps-migration-guide/ to migrate our current Travis CI usage.

If anyone knows of any gotchas with this, please let me know.

**Comment by annevk** [comment]
Hmm, so we haven't done this, but things still work. @foolip it seems you did this for web-platform-tests, thoughts?

**Comment by foolip** [comment]
I like GitHub Actions quite a bit more than Travis, but I'd recommend to wait until it exists beta in a few months since there are so many repos that have to be updated.

I'll request access to the beta for the whatwg org however, to allow experimenting before general availability.

**Comment by foolip** [comment]
Looks like someone already did that.

**Comment by annevk** [comment]
This is about continuing to use Travis, but as a GitHub App, because the old way supposedly was deprecated and removed. But I can't find evidence that we did any of that and things kept working...

**Comment by domenic** [comment]
I feel like Travis and GitHub managed to work together to effect a transparent migration. That kind of makes sense given how widespread Travis usage is.

**Comment by foolip** [comment]
Oh, sorry.

Yes I migrated from travis-ci.org to travis-ci.com for web-platform-tests, and it was fairly smooth. The main difference is it might change from using the old Statuses API to the new Checks API, which will change the name of the checks and require all branch protection rules to be updated. Also any existing PR would then have to be trigger CI again.

I wouldn't really recommend moving to travis-ci.com unless we're sure we'll stay on Travis for a long time and not migrate to GitHub Actions.

**Comment by annevk** [comment]
I guess I'm going to close this then.

**Comment by annevk** [comment]
Per https://docs.travis-ci.com/user/migrate/open-source-repository-migration this is still in beta so we should probably hold of for now, but given that the experience is more integrated with GitHub we should keep it in mind (or investigate a move to GitHub Actions I suppose, which is out of beta now I think).

**Comment by foolip** [comment]
At this point I would recommend migrating to GitHub Actions. It would be a fair bit of work since the CI steps aren't uniform between repos, however.

**Comment by foolip** [comment]
I've filed https://github.com/whatwg/meta/issues/173.

**Comment by annevk** [comment]
Closing in favor #173 as that seems pretty close and I don't see us looking back.
