### ISSUE TITLE
Make COMMITTING clearer

### ISSUE THREAD

**Issue by annevk** [whatwg/meta#97]
https://github.com/whatwg/meta/blob/master/COMMITTING.md

1. I'd like to add an example with default format of having a title and then a body with a link to tests and the issue it fixes. That pattern isn't really illustrated by the existing text.
2. I'm not sure we should enforce body line length. We have many squash commits where I'm not sure it's followed.

**Comment by domfarolino** [comment]
Just saw this, and definitely think it's a good idea.

**Comment by snuggs** [comment]
> 1. I'd like to add an example with default format of having a title and then a body with a link to tests and the issue it fixes. That pattern isn't really illustrated by the existing text.
@annevk i'll take a stab at this as I see many examples over at `wpt`. I'll prepare it as i'm sure you will do the final dressing up as we did initially.

> 2. I'm not sure we should enforce body line length. We have many squash commits where I'm not sure it's followed.
I thought about this for a few minutes and i'm still sitting on the fence. However legs dangling on the side of NOT enforcing length. To be clear assuming we are still enforcing 75chars for title YES?

**Comment by annevk** [comment]
@snuggs yeah, title should still fit and not cause an ellipsis to appear.

**Comment by snuggs** [comment]
Wow @annevk  i never even saw you responded as after a week I didn't check up on this. My bad!

Addressed in #119 

/cc @domfarolino
